Repository redhat-developer/gitops-operator, pull requests merged in 2021-06, with the labels that each got.

#122 added permissions to create resource quotas for gitops-operator
  deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#123 Rename `ArgoCD` link name to `Cluster Argo CD` to signif y…
  pkg/controller/argocd/argocd_controller.go
  pkg/controller/argocd/argocd_controller_test.go
Labels: approved, lgtm

#124 feat: GitOps Operator enables RHSSO for each ArgoCD Instance(#GITOPS-946)
  cmd/manager/main.go
  deploy/argocd_role.yaml
  deploy/crds/argoproj.io_argocds_crd.yaml
  deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  pkg/controller/argocd/argocd.go
  pkg/controller/argocd/argocd_test.go
  pkg/controller/gitopsservice/gitopsservice_controller.go
  pkg/controller/gitopsservice/gitopsservice_controller_test.go
Labels: approved, lgtm

#126 Add e2e tests to verify RHSSO Configuration
  test/e2e/gitops_service_test.go
  test/e2e/rhsso_test.go
Labels: approved, lgtm

#131 Make target for running e2e test on installed operator
  Makefile
  test/e2e/gitops_service_test.go
Labels: approved, kind/enhancement, lgtm

#134 Exit on test failure
  scripts/run_e2e_tests.sh
Labels: approved, lgtm

#127 Deploy a cluster scoped manifest e2e test coverage
  test/e2e/gitops_service_test.go
  test/e2e/kam_test.go
  test/e2e/rhsso_test.go
  test/examples/image/image.yaml
  test/helper/application_status.go
  test/yamls/image_appcr.yaml
Labels: approved, lgtm

#140 added identity-provider and application cr yamls for e2e test
  test/examples/identity-provider/identity-provider.yaml
  test/yamls/identity-provider_appcr.yaml
Labels: approved, kind/enhancement, lgtm

#141 Add E2E test for cluster-scoped namespace
  test/e2e/gitops_service_test.go
Labels: approved, lgtm

#144 fix: e2e tests failing locally (#143)
  go.mod
  go.sum
Labels: approved, lgtm

#142 e2e test for validation of argocd non-default namespace management - GITOPS-1005
  test/e2e/gitops_service_test.go
  test/helper/application_status.go
Labels: approved, kind/enhancement, lgtm

#149 Adding application CRs to appcrs directory
  test/appcrs/identity-provider_appcr.yaml
  test/appcrs/image_appcr.yaml
  test/appcrs/scheduler_appcr.yaml
Labels: approved, kind/enhancement, lgtm

#150 Update appcr path in test
  test/e2e/gitops_service_test.go
  test/yamls/identity-provider_appcr.yaml
  test/yamls/image_appcr.yaml
  test/yamls/scheduler_appcr.yaml
Labels: approved, kind/cleanup, lgtm
