Repository redhat-developer/gitops-operator, pull requests merged in 2021-10, with the labels that each got.

#233 fix: remove predicate from some watches
  controllers/gitopsservice_controller.go
Labels: lgtm, approved

#232 fix: remove predicate from some watches
  controllers/gitopsservice_controller.go
Labels: lgtm, approved

#234 sync argoproj-labs /argocd-operator from rhos-v1.3 branch and grab h…
  go.mod
  go.sum
Labels: kind/bug

#235 update applicationset crd to v0.2.0
  bundle/manifests/argoproj.io_applicationsets.yaml
  config/crd/bases/argoproj.io_applicationsets.yaml
Labels: kind/bug, lgtm, approved

#238 fix: add missing oauthclient permissions [cherry-pick into v1.3]
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/gitopsservice_controller.go
Labels: lgtm, approved
