Repository redhat-developer/gitops-operator, pull requests merged in 2021-08, with the labels that each got.

#188 chore: Add Apache 2.0 License
  LICENSE
Labels: lgtm, approved

#187 Add build application cr
  test/appcrs/build_appcr.yaml
  test/examples/build/base/build.yaml
Labels: kind/enhancement, lgtm, approved

#194 Use patches to add description and icon
  config/manifests/bases/gitops-operator.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
  config/manifests/patches/description.yaml
  config/manifests/patches/icon.yaml
Labels: lgtm, approved

#193 Update monitoring e2e test coverage
  test/e2e/argocd_metrics_test.go
Labels: kind/enhancement, lgtm, approved

#196 Add individual test target
  Makefile
Labels: kind/enhancement, lgtm, approved

#190 feat: Set the DISABLE_DEX environment variable to true in CSV
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  test/e2e/gitopsservice_test.go
  test/e2e/suite_test.go
  test/nondefaulte2e/suite_test.go
Labels: lgtm, approved

#200 Import openshift package from argocd-operator to enable hooks
  main.go
Labels: lgtm, approved

#197 Replace commands in the README with Makefile targets
  Makefile
  README.md
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: lgtm, approved

#202 fix some grammar errors/typos in README file
  README.md
Labels: kind/documentation, lgtm, approved

#198 Allow backend service role to access secrets
  controllers/gitopsservice_controller.go
  test/e2e/gitopsservice_test.go
Labels: lgtm, approved
