Repository redhat-developer/gitops-operator, pull requests merged in 2021-03, with the labels that each got.

#66 Pull it fix from argocd-operator to generate unqiue cluster resource name
  go.mod
  go.sum
Labels: approved, lgtm

#67 Fix comments in e2e test
  test/e2e/kam_test.go
Labels: approved, lgtm

#68 Mark GitOpsService CRD as internal
  deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#71 Teardown ArgoCD instance in E2E tests
  scripts/run_e2e_tests.sh
  test/e2e/gitops_service_test.go
Labels: approved, lgtm, ok-to-test

#72 GITOPS-650 - added ArgoCD CR example to add route in GitOps Operator CSV
  deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#73 Fix docker build command
  README.md
Labels: approved, lgtm

#78 Pick up from argocd operator "Upgraded ArgoCD version from 1.7.7 to 1.8.7"
  go.mod
  go.sum
Labels: approved, lgtm

#79 Revert "Mark GitOpsService CRD as internal (#68)"
  deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#74 Sync go version
  go.mod
  openshift-ci/build-root/Dockerfile
Labels: approved, lgtm

#80 Updating assets to reflect OpenShift GitOps Operator
  docs/assets/installed-operator.png
  docs/assets/operatorhub-listing.png
Labels: approved

#83 Update introduction in the readme
  README.md
Labels: approved, lgtm

#84 Updating docs
  README.md
Labels: approved, kind/documentation, lgtm, ok-to-test

#87 Sync argocd operator master
  go.mod
  go.sum
Labels: approved, kind/enhancement, lgtm

#86 Let user override operator-sdk binary for run-local target of Makefile
  Makefile
Labels: approved, lgtm

#88 Add ApplicationSet controller to gitops-operator
  deploy/crds/argoproj.io_applicationsets_crd.yaml
  deploy/crds/argoproj.io_argocds_crd.yaml
  deploy/olm-catalog/gitops-operator/manifests/argoproj.io_applicationsets_crd.yaml
  deploy/olm-catalog/gitops-operator/manifests/argoproj.io_argocds_crd.yaml
  deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
  pkg/controller/argocd/argocd.go
Labels: approved, kind/enhancement, lgtm

#89 Add Redis HA config files to operator image
  Dockerfile
  build/redis/haproxy.cfg.tpl
  build/redis/haproxy_init.sh.tpl
  build/redis/init.sh.tpl
  build/redis/redis.conf.tpl
  build/redis/sentinel.conf.tpl
Labels: approved, lgtm

#96 Removing unnecessary environment variable
  scripts/openshiftci-presubmit-all-tests.sh
  scripts/openshiftci-presubmit-unittests.sh
Labels: approved, lgtm, ok-to-test

#70 Rename OpenShift GitOps default Argo CD instance
  common/common.go
  deploy/argocd_clusterrole.yaml
  deploy/argocd_role.yaml
  deploy/argocd_role_binding.yaml
  deploy/argocd_service_account.yaml
  pkg/controller/argocd/argocd_controller.go
  pkg/controller/argocd/argocd_controller_test.go
  pkg/controller/argocdmetrics/argocd_metrics_controller_test.go
  pkg/controller/gitopsservice/gitopsservice_controller.go
  pkg/controller/gitopsservice/gitopsservice_controller_test.go
  test/e2e/gitops_service_test.go
Labels: approved, lgtm, ok-to-test

#97 Update new image registry path
  openshift-ci/build-root/Dockerfile
Labels: kind/failing-ci

#94 Upgrade to go 1.16
  Dockerfile
  go.mod
  go.sum
Labels: approved, kind/enhancement, lgtm, ok-to-test
