Repository redhat-developer/gitops-operator, pull requests merged in 2021-07, with the labels that each got.

#147 ApplicationHealthStatus and ApplicationSyncStatus are assuming that an empty health/sync string means it is healthy/synced
  scripts/run_e2e_tests.sh
  test/e2e/gitops_service_test.go
  test/helper/application_status.go
Labels: approved, lgtm

#135 e2e test for cluster config change - GITOPS-1003
  test/appcrs/scheduler_appcr.yaml
  test/e2e/gitops_service_test.go
  test/helper/application_status.go
  test/rolebindings/role-binding.yaml
  test/rolebindings/role.yaml
Labels: approved, kind/enhancement, lgtm

#137 Refactor GitopsService reconciler
  pkg/controller/gitopsservice/gitopsservice_controller.go
  pkg/controller/gitopsservice/gitopsservice_controller_test.go
Labels: approved, lgtm

#151 chore: update go.mod to point to latest upstream commit
  go.mod
  go.sum
Labels: approved, kind/enhancement, lgtm

#153 add a namespace scoped example for e2e
  test/appcrs/nginx_appcr.yaml
  test/examples/nginx/nginx.yaml
Labels: approved, lgtm

#152 e2e test to validate permissions granted by managed-by label
  test/e2e/gitops_service_test.go
  test/rolebindings/role-binding.yaml
  test/rolebindings/role.yaml
Labels: approved, lgtm

#155 feat: Add RHSSO support for OpenShift Disconnected Cluster
  deploy/crds/argoproj.io_argocds_crd.yaml
  go.mod
  go.sum
Labels: approved, lgtm

#156 add nginx appcr in openshift-gitops for e2e test
  test/appcrs/nginx_default_ns_appcr.yaml
Labels: approved, kind/enhancement, lgtm

#158 Add DISABLE_DEFAULT_ARGOCD_INSTANCE environment variable to operator to disable creation of default Argo CD instance
  Makefile
  common/common.go
  pkg/controller/gitopsservice/gitopsservice_controller.go
  pkg/controller/gitopsservice/gitopsservice_controller_test.go
  scripts/run_e2e_tests.sh
  test/e2e/gitops_service_test.go
  test/helper/application_status.go
  test/nondefaulte2e/gitops_service_nondefault_test.go
  test/nondefaulte2e/main_test.go
Labels: approved, kind/enhancement, lgtm

#160 feat: Do not install RHSSO OOTB for default Argo CD instance
  deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
  pkg/controller/argocd/argocd.go
  pkg/controller/argocd/argocd_test.go
  test/e2e/gitops_service_test.go
  test/e2e/rhsso_test.go
Labels: approved, lgtm

#163 sync argocd-operator fix: Remove admin permissions for ArgoCD instanc…
  go.mod
  go.sum
Labels: kind/enhancement

#164 Sync argocd operator to pick up: Add ability to specify Repo server image and tag (#358)
  deploy/olm-catalog/gitops-operator/manifests/argoproj.io_applications_crd.yaml
  deploy/olm-catalog/gitops-operator/manifests/argoproj.io_applicationsets_crd.yaml
  deploy/olm-catalog/gitops-operator/manifests/argoproj.io_appprojects_crd.yaml
  deploy/olm-catalog/gitops-operator/manifests/argoproj.io_argocds_crd.yaml
  go.mod
  go.sum
Labels: kind/enhancement

#157 add e2e test to validate permissions by label for OOTB argocd instance
  test/e2e/gitops_service_test.go
Labels: approved, lgtm

#165 bug: remove additional operator-backed items in the developer catalog
  deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#167 fix: Lower default CPU resource requests for better scheduling
  pkg/controller/argocd/argocd.go
  pkg/controller/argocd/argocd_test.go
Labels: approved, kind/bug, lgtm

#168 Pull the floowing fixes from argocd-operator: #364, #360
  deploy/crds/argoproj.io_argocds_crd.yaml
  go.mod
  go.sum
Labels: kind/bug

#161 Improve helper namespace deletion
  scripts/run_e2e_tests.sh
  test/e2e/gitops_service_test.go
  test/helper/application_status.go
  test/nondefaulte2e/gitops_service_nondefault_test.go
Labels: approved, kind/cleanup, lgtm

#170 fix: Argo CD installation from operator console fails as HA.Enabled is not set by default
  deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
  pkg/controller/argocd/argocd.go
  pkg/controller/argocd/argocd_test.go
Labels: approved, lgtm

#171 Revert "bug: remove additional operator-backed items in the developer…
  deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
Labels: approved, kind/bug, lgtm

#172 Pull in fixes from argocd operator: #362, #366
  deploy/crds/argoproj.io_argocds_crd.yaml
  deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
  go.mod
  go.sum
Labels: kind/bug, kind/enhancement

#162 add e2e test for validating revoking of permissions by removing namespace label
  test/e2e/gitops_service_test.go
Labels: approved, lgtm

#173 fix: Align default resource limits with instances created in DevConsole
  deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
Labels: approved, kind/bug, lgtm

#174 Pull in fix: Keycloak fails to update OIDC config in argocd-cm inte…
  go.mod
  go.sum
Labels: kind/bug

#175 fix: Updated RHSSO failing tests for make target "test-e2e-on-operator"
  test/e2e/rhsso_test.go
Labels: approved, lgtm

#176 Pull in fix: delete existing RBACs when namespace label is updated (#…
  go.mod
  go.sum
Labels: approved, lgtm

#178 fix: Pull in #372 from argocd-operator
  go.mod
  go.sum
Labels: approved, lgtm

#179 fix: set resource requirements to containers incase of the operator upgrade
  go.mod
  go.sum
  pkg/controller/gitopsservice/gitopsservice_controller.go
  pkg/controller/gitopsservice/gitopsservice_controller_test.go
  pkg/controller/gitopsservice/kam.go
Labels: approved, lgtm

#181 fix: update opencontainers/runc to fix security vulnerabilities reported by dependabot (#180)
  go.mod
  go.sum
Labels: approved, lgtm

#182 chore: fix runc security vulnerability reported by dependabot
  go.mod
  go.sum
Labels: approved, lgtm
