Repository redhat-developer/gitops-operator, pull requests merged in 2021-09, with the labels that each got.

#204 feat: Configure OpenShift Login for Dex OOTB
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/samples/argoproj.io_v1alpha1_argocd.yaml
  controllers/argocd/argocd.go
  controllers/argocd/argocd_test.go
Labels: lgtm, approved

#205 fix: issues with resource quota and resource requirements
  controllers/argocd/argocd.go
  controllers/argocd/argocd_test.go
  controllers/gitopsservice_controller.go
  controllers/gitopsservice_controller_test.go
Labels: lgtm, approved

#209 chore: update operator-sdk to v1.11.0
  bundle.Dockerfile
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  bundle/manifests/gitops-operator_v1_serviceaccount.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
Labels: lgtm, approved

#210 Update argocd-operator version
  controllers/argocd/argocd.go
  controllers/argocd/argocd_test.go
  controllers/argocd_controller.go
  controllers/argocd_controller_test.go
  controllers/argocd_metrics_controller.go
  controllers/argocd_metrics_controller_test.go
  controllers/gitopsservice_controller.go
  controllers/gitopsservice_controller_test.go
  go.mod
  go.sum
  main.go
  test/e2e/gitopsservice_test.go
  test/e2e/suite_test.go
  test/helper/application_status.go
  test/nondefaulte2e/gitops_service_nondefault_test.go
  test/nondefaulte2e/suite_test.go
Labels: lgtm, approved

#213 chore: update repo server resource limit in argocd sample
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/samples/argoproj.io_v1alpha1_argocd.yaml
Labels: lgtm, approved

#212 Use the latest operator-sdk naming convention
  bundle/manifests/gitops-operator-controller-manager-metrics-service_v1_service.yaml
  bundle/manifests/gitops-operator-manager-config_v1_configmap.yaml
  bundle/manifests/gitops-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/default/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
Labels: lgtm, approved

#214 fix: issues with resource quota and resource requirements (v1.2.1)
  deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
  pkg/controller/argocd/argocd.go
  pkg/controller/argocd/argocd_test.go
  pkg/controller/gitopsservice/gitopsservice_controller.go
  pkg/controller/gitopsservice/gitopsservice_controller_test.go
Labels: lgtm, approved

#185 feat: Support application controller sharding, pull #384 from argocd-operator
  bundle/manifests/argoproj.io_argocds.yaml
  config/crd/bases/argoproj.io_argocds.yaml
Labels: lgtm, approved

#218 chore: Restore logic to add resource limits to workloads incase of operator upgrades.
  controllers/gitopsservice_controller.go
  controllers/gitopsservice_controller_test.go
Labels: lgtm, approved

#219 update argocd-operator to latest commit
  go.mod
  go.sum
Labels: kind/enhancement, lgtm, approved

#217 chore: update steps to run operator locally
  README.md
Labels: lgtm, approved

#220 Sync up CRDs from upstream argocd operator
  bundle/manifests/argoproj.io_applicationsets.yaml
  bundle/manifests/argoproj.io_argocds.yaml
  config/crd/bases/argoproj.io_applicationsets.yaml
  config/crd/bases/argoproj.io_argocds.yaml
Labels: kind/enhancement

#223 fix: Add permissions to the operator to delete resourcequotas.
  deploy/argocd_role.yaml
  deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#215 feat: add toggle to enable openshift infra node and tolerations
  api/v1alpha1/gitopsservice_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  common/common.go
  config/crd/bases/pipelines.openshift.io_gitopsservices.yaml
  controllers/gitopsservice_controller.go
  controllers/gitopsservice_controller_test.go
  controllers/kam.go
  test/e2e/gitopsservice_test.go
Labels: lgtm, approved

#225 Pull in changes from argocd-operator
  go.mod
  go.sum
Labels: lgtm, approved

#226 chore: Update bundle manifests
  bundle/manifests/argoproj.io_argocds.yaml
  bundle/manifests/pipelines.openshift.io_gitopsservices.yaml
  config/crd/bases/argoproj.io_argocds.yaml
Labels: kind/enhancement, lgtm, approved

#227 chore: Increase the default timeout for e2e tests
  Makefile
Labels: lgtm, approved

#231 chore: pickup multiple sso validation
  bundle/manifests/argoproj.io_argocds.yaml
  config/crd/bases/argoproj.io_argocds.yaml
  go.mod
  go.sum
  test/e2e/gitopsservice_test.go
Labels: kind/enhancement, lgtm, approved

#230 fix: Add permissions to operator to delete ResourceQuota object on namespace
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/gitopsservice_controller.go
Labels: lgtm, approved
