Repository redhat-developer/gitops-operator, pull requests merged in 2021-02, with the labels that each got.

#40 fix indentation
  deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#41 Register Prometheus monitoring API scheme
  cmd/manager/main.go
  go.mod
Labels: approved, lgtm

#43 Watch for argocd route in the right namespace
  pkg/controller/argocd/argocd.go
  pkg/controller/argocd/argocd_controller.go
  pkg/controller/argocd/argocd_controller_test.go
  pkg/controller/gitopsservice/gitopsservice_controller.go
  pkg/controller/gitopsservice/gitopsservice_controller_test.go
  pkg/controller/util/util.go
  pkg/controller/util/util_test.go
  scripts/run_e2e_tests.sh
  test/e2e/gitops_service_test.go
Labels: approved, lgtm

#42 Disable dex by default
  deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#29 Setup ArgoCD out of the box in the "openshift-gitops"
  go.mod
  pkg/controller/argocd/argocd.go
  pkg/controller/argocd/argocd_controller.go
  pkg/controller/argocd/argocd_controller_test.go
  pkg/controller/gitopsservice/gitopsservice_controller.go
  pkg/controller/gitopsservice/gitopsservice_controller_test.go
  pkg/controller/util/util.go
  pkg/controller/util/util_test.go
  scripts/run_e2e_tests.sh
  test/e2e/gitops_service_test.go
Labels: approved, lgtm

#27 Serve kam CLI
  pkg/controller/gitopsservice/gitopsservice_controller.go
  pkg/controller/gitopsservice/gitopsservice_controller_test.go
  pkg/controller/gitopsservice/kam.go
  test/e2e/gitops_service_test.go
  test/e2e/kam_test.go
Labels: approved, lgtm

#48 Fix default kam CLI image
  pkg/controller/gitopsservice/kam.go
Labels: approved, lgtm

#46 Fix Argo CD installation namespace for a 4.6 cluster
  pkg/controller/argocd/argocd.go
  pkg/controller/argocd/argocd_controller.go
  pkg/controller/gitopsservice/gitopsservice_controller.go
  pkg/controller/gitopsservice/gitopsservice_controller_test.go
  test/e2e/gitops_service_test.go
Labels: approved, lgtm

#47 Use Red Hat provided redis image as default
  deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
Labels: approved, lgtm, ok-to-test

#49 Add permission to create console download link resource
  deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm

#50 pick up reconcile redis/dex fixes from upstream argocd operator
  go.mod
  go.sum
Labels: approved, lgtm, needs-ok-to-test

#53 Fix e2e test for kam CLI link
  test/e2e/kam_test.go
Labels: approved, lgtm

#51 Rename "Application Stages" to "OpenShift GitOps"
  pkg/controller/argocd/argocd_controller.go
Labels: approved, lgtm

#52 pick up upstream fixes for dex reconcile
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test

#57 Enable gitops e2e test
  Makefile
  scripts/install-operator-sdk.sh
  scripts/openshiftci-presubmit-all-tests.sh
  scripts/prepare-test-cluster.sh
Labels: approved, lgtm

#54 Add controller to enable metrics/alerts for argocd instances
  deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
  pkg/controller/add_argocd_metrics.go
  pkg/controller/argocdmetrics/argocd_metrics_controller.go
  pkg/controller/argocdmetrics/argocd_metrics_controller_test.go
  test/e2e/gitops_service_test.go
Labels: approved, lgtm, ok-to-test

#59 Update Argo CD operator version
  go.mod
  go.sum
Labels: approved, lgtm

#60 Pull in Pipelines v1.3.0 for OCP 4.7
  deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#61 fix spacing
  deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#63 Pull in dex clientID fix from argocd-operator@master
  go.mod
  go.sum
Labels: approved, lgtm

#65 Inject git commit into binary
  Dockerfile
  cmd/manager/main.go
Labels: approved, lgtm
