Repository redhat-developer/gitops-operator, pull requests merged in 2022-07, with the labels that each got.

#344 Update argocd-operator depenedency
  go.mod
  go.sum
Labels: kind/cleanup

#333 feat: implement ability to disable default argocd consoleLink
  common/common.go
  controllers/argocd_controller.go
  controllers/argocd_controller_test.go
  docs/OpenShift GitOps Usage Guide.md
Labels: lgtm, approved

#350 fix: backport 4.11 fixes to v1.4
  go.mod
  go.sum
Labels: kind/bug

#351 fix: backport 4.11 fixes to v1.5
  go.mod
  go.sum
Labels: kind/bug

#348 add documentation for new DCO requirements
  CONTRIBUTING.md
Labels: lgtm, approved
