Repository redhat-developer/gitops-operator, pull requests merged in 2022-08, with the labels that each got.

#354 fix: operator resource labels should be unique
  bundle/manifests/gitops-operator-controller-manager-metrics-service_v1_service.yaml
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_service.yaml
  test/e2e/gitopsservice_test.go
Labels: lgtm, approved

#353 docs: Update user guide workload permissions
  docs/OpenShift GitOps Usage Guide.md
Labels: kind/documentation

#360 add .vscode/ to .gitignore
  .gitignore
Labels: kind/enhancement, lgtm, approved

#341 Fix haproxy crash part 2 (master)
  .gitignore
  controllers/argocd/openshift/openshift.go
  controllers/argocd/openshift/openshift_test.go
  go.mod
  go.sum
Labels: kind/bug, lgtm, approved
