Repository redhat-developer/gitops-operator, pull requests merged in 2022-11, with the labels that each got.

#392 fix: update rbac.authorization verbs, update argocd sha
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/gitopsservice_controller.go
  go.mod
  go.sum
Labels: lgtm, approved

#394 fix: applicationset container port for metrics
  go.mod
  go.sum
Labels: kind/bug, lgtm, approved

#395 chore: update argocd-operator version and respective crds
  Makefile
  bundle/manifests/argoproj.io_applications.yaml
  bundle/manifests/argoproj.io_applicationsets.yaml
  bundle/manifests/argoproj.io_appprojects.yaml
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/crd/bases/argoproj.io_applications.yaml
  config/crd/bases/argoproj.io_applicationsets.yaml
  config/crd/bases/argoproj.io_appprojects.yaml
  config/rbac/role.yaml
  controllers/gitopsservice_controller.go
  go.mod
  go.sum
Labels: kind/enhancement, lgtm, approved

#391 Removing 'Validate granting permissions by label' test
  test/e2e/gitopsservice_test.go
Labels: lgtm, approved, kind/failing-test

#387 Gitops 1323 config dynamic plugin
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  common/common.go
  config/manifests/bases/gitops-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/consoleplugin.go
  controllers/consoleplugin_test.go
  controllers/gitopsservice_controller.go
  controllers/gitopsservice_controller_test.go
  controllers/kam.go
  controllers/util/util.go
  go.mod
  go.sum
  main.go
Labels: kind/enhancement, approved

#400 chore: pick up latest argocd-operator commit
  go.mod
  go.sum
Labels: lgtm

#402 Add reconcile plugin condition
  common/common.go
  controllers/gitopsservice_controller.go
  controllers/gitopsservice_controller_test.go
  go.mod
  go.sum
Labels: kind/enhancement, lgtm, approved

#403 [cherry-pick]: Add reconcile plugin condition (#402)
  common/common.go
  controllers/gitopsservice_controller.go
  controllers/gitopsservice_controller_test.go
  go.mod
  go.sum
Labels: approved
