Repository redhat-developer/gitops-operator, pull requests merged in 2022-06, with the labels that each got.

#329 feat: Unify SSO configuration under `.spec.sso` in backward compatible way
  bundle/manifests/argoproj.io_argocds.yaml
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/crd/bases/argoproj.io_argocds.yaml
  config/samples/argoproj.io_v1alpha1_argocd.yaml
  controllers/argocd/argocd.go
  controllers/argocd/argocd_test.go
  controllers/gitopsservice_controller.go
  controllers/gitopsservice_controller_test.go
  go.mod
  go.sum
  test/e2e/gitopsservice_test.go
Labels: kind/enhancement, lgtm, approved

#318 docs: Update user guide notifications
  docs/OpenShift GitOps Usage Guide.md
Labels: kind/documentation, lgtm, approved

#332 chore: update to latest argocd-operator
  go.mod
  go.sum
Labels: lgtm, approved, kind/cleanup

#335 Fix openshift haproxy crash (1.6)
  controllers/argocd/openshift/openshift.go
  controllers/argocd/openshift/openshift_test.go
Labels: kind/bug
