Repository redhat-developer/gitops-operator, pull requests merged in 2022-05, with the labels that each got.

#295 refactoring: move openshift package from argocd-operator to gitops-operator
  controllers/argocd/openshift/clusterconfig_test.go
  controllers/argocd/openshift/openshift.go
  controllers/argocd/openshift/openshift_test.go
  go.mod
  main.go
Labels: lgtm, approved

#310 Adding .ci-operator file
  .ci-operator.yaml
Labels: lgtm, approved

#309 Upgrade argocd-operator version in go.mod
  bundle/manifests/argoproj.io_applications.yaml
  bundle/manifests/argoproj.io_applicationsets.yaml
  bundle/manifests/argoproj.io_appprojects.yaml
  bundle/manifests/argoproj.io_argocds.yaml
  config/crd/bases/argoproj.io_applications.yaml
  config/crd/bases/argoproj.io_applicationsets.yaml
  config/crd/bases/argoproj.io_argocds.yaml
  go.mod
  go.sum
Labels: lgtm, approved, do-not-merge/hold

#311 chore: upgrade to redis 6
  build/redis/haproxy.cfg.tpl
  build/redis/init.sh.tpl
  build/redis/redis.conf.tpl
  build/redis/redis_liveness.sh.tpl
  build/redis/redis_readiness.sh.tpl
  build/redis/sentinel.conf.tpl
  build/redis/sentinel_liveness.sh.tpl
Labels: kind/enhancement, lgtm, approved

#317 reverted ls and fix read go version
  Makefile
Labels: lgtm, approved

#320 changed Dockerfile to 1.18
  openshift-ci/build-root/Dockerfile
Labels: lgtm, approved

#319 set empty goflag for 1.18
  Makefile
Labels: lgtm, approved

#307 chore: upgrade go version
  Dockerfile
  Makefile
  controllers/argocd/openshift/clusterconfig_test.go
  go.mod
  go.sum
  test/e2e/gitopsservice_test.go
  test/e2e/suite_test.go
Labels: lgtm, approved, ok-to-test
