Repository redhat-developer/gitops-operator, pull requests merged in 2023-05, with the labels that each got.

#498 bug: pickup hpa reconciliation fixes for v1.8.3
  go.mod
  go.sum
Labels: lgtm, approved

#501 GitOps-2675: Upgrade go version to v1.19
  .ci-operator.yaml
  Dockerfile
  Makefile
  api/v1alpha1/groupversion_info.go
  go.mod
  go.sum
  openshift-ci/build-root/Dockerfile
Labels: lgtm, approved

#509 fix: Unblock the build process for release branch
  Dockerfile
  bundle/bundle.Dockerfile
  config/manager/manager.yaml
Labels: lgtm, approved

#513 CI failure: Fixing Kuttl tests
  test/openshift/e2e/parallel/1-038_validate_productized_images/02-check-images.yaml
  test/openshift/e2e/parallel/1-090_validate_permissions/01-assert.yaml
  test/openshift/e2e/sequential/1-031_validate_toolchain/01-check.yaml
  test/openshift/e2e/sequential/1-085_validate_dynamic_plugin_installation/02-install-dynamic-plugin.yaml
Labels: lgtm, approved

#503 docs: Update doc to reflect extended support for sso deprecated fields
  docs/OpenShift GitOps Usage Guide.md
Labels: kind/documentation, ok-to-test

#510 fix: minor fixes in non-olm install script and doc
  hack/non-olm-install/README.md
  hack/non-olm-install/install-gitops-operator.sh
Labels: approved

#516 Update CRD, bundle changes and argocd-operator version
  bundle.Dockerfile
  bundle/manifests/argoproj.io_applications.yaml
  bundle/manifests/argoproj.io_applicationsets.yaml
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/argoproj.io_applications.yaml
  config/crd/bases/argoproj.io_applicationsets.yaml
  config/crd/bases/argoproj.io_appprojects.yaml
  config/manifests/patches/description.yaml
  go.mod
  go.sum
  test/openshift/e2e/parallel/1-045_validate_repo_exec_timeout/04-check-workload-env.yaml
Labels: kind/enhancement, lgtm, approved

#440 Promote ConsolePlugin API version to v1
  controllers/consoleplugin.go
  controllers/consoleplugin_test.go
  controllers/gitopsservice_controller_test.go
  main.go
Labels: kind/enhancement

#519 chore: Update argocd-operator to include ha reconciliation fix
  go.mod
  go.sum
Labels: kind/bug, lgtm, approved, ok-to-test
