Repository redhat-developer/gitops-operator, pull requests merged in 2023-04, with the labels that each got.

#485 chore: pick up latest argocd-operator commit for v1.8 branch
  go.mod
  go.sum
Labels: lgtm, approved

#484 Added script to install Openshift Gitops Operator without the OLM
  hack/non-olm-install/README.md
  hack/non-olm-install/install-gitops-operator.sh
  hack/non-olm-install/rbac-patch.yaml
Labels: lgtm, ok-to-test

#491 Onboading Interop testing on Openshift CI
  scripts/openshift-Interop-kuttl-tests.sh
Labels: kind/enhancement, lgtm, approved

#492 Adding execution permission to interop testing script
  scripts/openshift-interop-kuttl-tests.sh
Labels: lgtm, approved

#479 fix: add argoproj.io rules in rbac for non-olm install
  controllers/argocd/openshift/openshift.go
Labels: lgtm, approved
