Repository redhat-developer/gitops-operator, pull requests merged in 2023-03, with the labels that each got.

#452 fix: add security context for kam and cluster pods
  controllers/gitopsservice_controller.go
  controllers/gitopsservice_controller_test.go
  controllers/kam.go
  controllers/util/util.go
Labels: approved

#453 Changing naming conventions
  Makefile
  README.md
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/gitops-operator.clusterserviceversion.yaml
  scripts/openshiftci-olm-kuttl-tests.sh
Labels: lgtm, approved

#458 fix: handle kam security context during upgrades
  controllers/gitopsservice_controller.go
  controllers/kam.go
Labels: lgtm, approved

#463 feat: update Argo CD version to 2.6.7
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/manifests/patches/description.yaml
Labels: lgtm, approved

#467 Changing naming conventions for v1.8
  Makefile
  README.md
  bundle.Dockerfile
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/gitops-operator.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
  scripts/openshiftci-olm-kuttl-tests.sh
Labels: lgtm, approved

#468 fix: Reconcile Dex client secret when .spec.dex is set
  go.mod
  go.sum
  test/openshift/e2e/parallel/1-098_validate_dex_clientsecret_deprecated/01-assert.yaml
  test/openshift/e2e/parallel/1-098_validate_dex_clientsecret_deprecated/01-install.yaml
  test/openshift/e2e/parallel/1-098_validate_dex_clientsecret_deprecated/02-verify-clientsecret.yaml
Labels: lgtm, approved

#459 fix: handle kam security context during upgrades
  controllers/gitopsservice_controller.go
  controllers/kam.go
Labels: approved

#451 fix: add security context to kam and cluster pods
  controllers/gitopsservice_controller.go
  controllers/gitopsservice_controller_test.go
  controllers/kam.go
  controllers/util/util.go
Labels: lgtm, approved

#473 fix: add security context to kam and cluster pods
  controllers/gitopsservice_controller.go
  controllers/gitopsservice_controller_test.go
  controllers/kam.go
  controllers/util/util.go
Labels: kind/enhancement, lgtm, approved

#471 chore: Pull latest version of argo-cd operator
  go.mod
  go.sum
Labels: kind/enhancement, lgtm, approved

#476 chore: Pull latest version of argo-cd operator
  go.mod
  go.sum
Labels: lgtm, approved
