Repository redhat-developer/gitops-operator, pull requests merged in 2023-02, with the labels that each got.

#427 feat: Add default channel and bundle channels for 1.8
  Makefile
  bundle.Dockerfile
  bundle/metadata/annotations.yaml
Labels: lgtm

#432 fix: upgrade `goutils` to `v1.1.1` to address CVE-2021-4238 [v1.7]
  api/v1alpha1/zz_generated.deepcopy.go
  go.mod
  go.sum
Labels: approved

#431 fix: upgrade `goutils` to `v1.1.1` to address CVE-2021-4238 [v1.6]
  go.mod
  go.sum
Labels: approved

#430 fix: upgrade `goutils` to `v1.1.1` to address CVE-2021-4238 [v1.5]
  go.mod
  go.sum
Labels: approved

#439 update argocd-operator to latest version
  go.mod
  go.sum
Labels: lgtm, approved

#438 Fix failing Kuttl tests
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/manifests/bases/gitops-operator.clusterserviceversion.yaml
  test/openshift/e2e/parallel/1-038_validate_productized_images/02-check-images.yaml
  test/openshift/e2e/parallel/1-090_validate_permissions/01-assert.yaml
  test/openshift/e2e/sequential/1-018_validate_disable_default_instance/04-assert.yaml
  test/openshift/e2e/sequential/1-031_validate_toolchain/01-check.yaml
  test/openshift/e2e/sequential/1-077_validate_workload_status_monitoring_alert/02-verify-alert.yaml
  test/openshift/e2e/sequential/1-085_validate_dynamic_plugin_installation/02-install-dynamic-plugin.yaml
Labels: lgtm, approved

#442 Fixing tests for Openshift CI compatibility
  bundle.Dockerfile
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  test/openshift/e2e/parallel/1-090_validate_permissions/01-assert.yaml
  test/openshift/e2e/sequential/1-031_validate_toolchain/01-check.yaml
  test/openshift/e2e/sequential/1-084_validate_prune_templates/01-assert.yaml
  test/openshift/e2e/sequential/1-084_validate_prune_templates/01-create-ns-managed-by.yaml
  test/openshift/e2e/sequential/1-084_validate_prune_templates/02-prune-duplicateGVK-resource.yaml
  test/openshift/e2e/sequential/1-084_validate_prune_templates/03-errors.yaml
  test/openshift/e2e/sequential/1-084_validate_prune_templates/04-delete.yaml
Labels: lgtm

#443 Correcting CSV name in 1-090_validate_permissions
  test/openshift/e2e/parallel/1-090_validate_permissions/01-assert.yaml
  test/openshift/e2e/sequential/1-077_validate_workload_status_monitoring_alert/02-verify-alert.yaml
Labels: kind/failing-test

#445 Disabling workload-status-monitoring test
  test/openshift/e2e/sequential/1-077_validate_workload_status_monitoring_alert/01-assert.yaml
  test/openshift/e2e/sequential/1-077_validate_workload_status_monitoring_alert/01-install.yaml
  test/openshift/e2e/sequential/1-077_validate_workload_status_monitoring_alert/02-verify-alert.yaml
Labels: lgtm, kind/failing-test
