Repository redhat-developer/gitops-operator, pull requests merged in 2023-11, with the labels that each got.

#619 Fix dynamic plugin test for OCP 4.15
  test/openshift/e2e/sequential/1-085_validate_dynamic_plugin_installation/01-errors.yaml
  test/openshift/e2e/sequential/1-085_validate_dynamic_plugin_installation/01-install-dynamic-plugin.yaml
Labels: lgtm, approved

#622 fix: reconcile operator metrics service monitor based on installation namespace
  controllers/argocd_controller.go
  controllers/argocd_metrics_controller.go
Labels: lgtm, approved

#621 Add a link to the migration guide
  README.md
Labels: kind/documentation, needs-ok-to-test

#617 updating tests to work with mac
  scripts/e2e-common.sh
  test/openshift/e2e/ignore-tests/sequential/1-064_validate_tcp_reset_error/03-wait.yaml
  test/openshift/e2e/parallel/1-008_validate-custom-argocd-namespace/02-wait.yaml
  test/openshift/e2e/parallel/1-025-validate-managed-by-change/02-wait.yaml
  test/openshift/e2e/parallel/1-030_validate_reencrypt/02-wait.yaml
  test/openshift/e2e/parallel/1-043_validate_log_level_format/03-check-loglevel.yaml
  test/openshift/e2e/parallel/1-049_validate_parallelism_limit/02-check-deployment.yaml
  test/openshift/e2e/parallel/1-049_validate_parallelism_limit/04-check-deployment.yaml
  test/openshift/e2e/parallel/1-049_validate_parallelism_limit/06-check-deployment.yaml
  test/openshift/e2e/parallel/1-058_validate_prometheus_rule/02-wait.yaml
  test/openshift/e2e/parallel/1-066_validate_redis_secure_comm_no_autotls_no_ha/02-generate_cert.yaml
  test/openshift/e2e/parallel/1-067_validate_redis_secure_comm_no_autotls_ha/02-generate_cert.yaml
Labels: kind/failing-test

#607 feat: Add labelSelector option to filter the ArgoCD instances for reconciliation
  common/common.go
  config/manager/manager.yaml
  hack/non-olm-install/README.md
  hack/non-olm-install/install-gitops-operator.sh
  main.go
  test/openshift/e2e/sequential/1-105_validate_label_selector/01-add-label-selector.yaml
  test/openshift/e2e/sequential/1-105_validate_label_selector/02-errors.yaml
  test/openshift/e2e/sequential/1-105_validate_label_selector/02-install.yaml
  test/openshift/e2e/sequential/1-105_validate_label_selector/03-add-label.yaml
  test/openshift/e2e/sequential/1-105_validate_label_selector/03-assert.yaml
  test/openshift/e2e/sequential/1-105_validate_label_selector/04-assert.yaml
  test/openshift/e2e/sequential/1-105_validate_label_selector/04-install.yaml
  test/openshift/e2e/sequential/1-105_validate_label_selector/05-remove-label.yaml
  test/openshift/e2e/sequential/1-105_validate_label_selector/06-assert.yaml
  test/openshift/e2e/sequential/1-105_validate_label_selector/06-errors.yaml
  test/openshift/e2e/sequential/1-105_validate_label_selector/06-install.yaml
  test/openshift/e2e/sequential/1-105_validate_label_selector/07-remove-label-selector.yaml
Labels: kind/enhancement, approved

#593 fix: Remove premature removal of finalizer from Default ArgoCD Instance
  controllers/gitopsservice_controller.go
  test/openshift/e2e/ignore-tests/sequential/1-018_validate_disable_default_instance/01-assert.yaml
  test/openshift/e2e/ignore-tests/sequential/1-018_validate_disable_default_instance/02-assert.yaml
  test/openshift/e2e/ignore-tests/sequential/1-018_validate_disable_default_instance/02-patch-subscription.yaml
  test/openshift/e2e/ignore-tests/sequential/1-018_validate_disable_default_instance/03-check.yaml
  test/openshift/e2e/ignore-tests/sequential/1-018_validate_disable_default_instance/04-assert.yaml
  test/openshift/e2e/ignore-tests/sequential/1-018_validate_disable_default_instance/04-patch-subscription.yaml
  test/openshift/e2e/ignore-tests/sequential/1-018_validate_disable_default_instance/errors.yaml
Labels: lgtm

#592 fix: Remove premature removal of finalizer from Default ArgoCD Instance
  controllers/gitopsservice_controller.go
  test/openshift/e2e/ignore-tests/sequential/1-018_validate_disable_default_instance/01-assert.yaml
  test/openshift/e2e/ignore-tests/sequential/1-018_validate_disable_default_instance/02-assert.yaml
  test/openshift/e2e/ignore-tests/sequential/1-018_validate_disable_default_instance/02-patch-subscription.yaml
  test/openshift/e2e/ignore-tests/sequential/1-018_validate_disable_default_instance/03-check.yaml
  test/openshift/e2e/ignore-tests/sequential/1-018_validate_disable_default_instance/04-assert.yaml
  test/openshift/e2e/ignore-tests/sequential/1-018_validate_disable_default_instance/04-patch-subscription.yaml
  test/openshift/e2e/ignore-tests/sequential/1-018_validate_disable_default_instance/errors.yaml
Labels: lgtm

#626 Fix dynamic plugin test for OCP 4.15
  test/openshift/e2e/sequential/1-085_validate_dynamic_plugin_installation/01-errors.yaml
  test/openshift/e2e/sequential/1-085_validate_dynamic_plugin_installation/01-install-dynamic-plugin.yaml
Labels: lgtm, approved, kind/failing-test
