Repository redhat-developer/gitops-operator, pull requests merged in 2023-10, with the labels that each got.

#482 test: use `t.Setenv` to set env vars
  controllers/argocd/openshift/clusterconfig_test.go
  controllers/argocd/openshift/openshift_test.go
  controllers/argocd_controller_test.go
  controllers/gitopsservice_controller_test.go
Labels: lgtm, approved, ok-to-test, kind/cleanup

#612 chore: port cve fix from master
  .ci-operator.yaml
  Dockerfile
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
  controllers/argocd_metrics_controller_test.go
  controllers/gitopsservice_controller_test.go
  go.mod
  go.sum
  main.go
  test/e2e/suite_test.go
  test/nondefaulte2e/suite_test.go
Labels: lgtm, approved

#611 fix: address CVE-2023-39325
  .ci-operator.yaml
  Dockerfile
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
  controllers/argocd_metrics_controller_test.go
  controllers/gitopsservice_controller_test.go
  go.mod
  go.sum
  main.go
  test/e2e/suite_test.go
  test/nondefaulte2e/suite_test.go
Labels: kind/enhancement, lgtm, approved

#614 chore: update kube-rbac-proxy args to disable http2
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
Labels: lgtm, approved
