Repository redhat-developer/gitops-operator, pull requests merged in 2023-07, with the labels that each got.

#549 fix test for 1.7
  test/openshift/e2e/sequential/1-018_validate_disable_default_instance/02-patch-subscription.yaml
  test/openshift/e2e/sequential/1-034_validate_custom_roles/02-patch-subscription.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/04-disable-dex-through-sub.yaml
  test/openshift/e2e/sequential/1-056_validate_managed-by/04-add_env.yaml
Labels: kind/failing-test

#546 add QE manager and team members as Approver and Reviewer
  OWNERS
Labels: lgtm, approved

#552 fix e2e sequestial failing test
  test/openshift/e2e/sequential/1-018_validate_disable_default_instance/03-patch-subscription.yaml
  test/openshift/e2e/sequential/1-034_validate_custom_roles/06-revert-patch.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/05-unset-disable-dex-env-var.yaml
  test/openshift/e2e/sequential/1-056_validate_managed-by/07-remove_env.yaml
Labels: kind/failing-test

#555 fix other failing tests
  test/openshift/e2e/parallel/1-066_validate_redis_secure_comm_no_autotls_no_ha/02-generate_cert.yaml
  test/openshift/e2e/sequential/1-056_validate_managed-by/04-assert.yaml
Labels: kind/failing-test

#558 Fix kuttl tests for v1.7
  test/openshift/e2e/parallel/1-030_validate_reencrypt/03-check-route.yaml
  test/openshift/e2e/parallel/1-066_validate_redis_secure_comm_no_autotls_no_ha/03-create_secret.yaml
  test/openshift/e2e/parallel/1-066_validate_redis_secure_comm_no_autotls_no_ha/05-check_deployments.yaml
  test/openshift/e2e/sequential/1-042_validate_status_host/03-assert.yaml
  test/openshift/e2e/sequential/1-042_validate_status_host/03-modify_route_URL.yaml
Labels: kind/failing-test

#531 Support migration to non-OLM installation and using regctl for extracting CSV info from bundle image
  hack/non-olm-install/README.md
  hack/non-olm-install/install-gitops-operator.sh
Labels: kind/enhancement, lgtm, approved

#534 Add Kuttl tests
  test/openshift/e2e/parallel/1-095_validate_dex_clientsecret/01-assert.yaml
  test/openshift/e2e/parallel/1-095_validate_dex_clientsecret/01-install.yaml
  test/openshift/e2e/parallel/1-095_validate_dex_clientsecret/02-check-clientSecret-cm.yaml
  test/openshift/e2e/parallel/1-095_validate_dex_clientsecret/03-verify-clientsecret-secret.yaml
  test/openshift/e2e/parallel/1-099_validate_server_autoscale/01-assert.yaml
  test/openshift/e2e/parallel/1-099_validate_server_autoscale/01-install.yaml
  test/openshift/e2e/parallel/1-099_validate_server_autoscale/02-enable-server-autoscale.yaml
  test/openshift/e2e/parallel/1-099_validate_server_autoscale/03-check-server-replicas.yaml
  test/openshift/e2e/parallel/1-099_validate_server_autoscale/04-assert.yaml
  test/openshift/e2e/parallel/1-099_validate_server_autoscale/04-update-hpa.yaml
  test/openshift/e2e/parallel/1-100_validate_rollouts_resources_creation/01-assert.yaml
  test/openshift/e2e/parallel/1-100_validate_rollouts_resources_creation/01-install-rolloutmanager.yaml
  test/openshift/e2e/parallel/1-100_validate_rollouts_resources_creation/02-assert.yaml
  test/openshift/e2e/parallel/1-101_validate_rollout_policyrules/01-assert.yaml
  test/openshift/e2e/parallel/1-101_validate_rollout_policyrules/01-install-rollloutmanager.yaml
  test/openshift/e2e/parallel/1-102_validate_handle_terminating_namespaces/01-assert.yaml
  test/openshift/e2e/parallel/1-102_validate_handle_terminating_namespaces/01-install.yaml
  test/openshift/e2e/parallel/1-102_validate_handle_terminating_namespaces/02-assert.yaml
  test/openshift/e2e/parallel/1-102_validate_handle_terminating_namespaces/02-install.yaml
  test/openshift/e2e/parallel/1-102_validate_handle_terminating_namespaces/03-delete-ns.yaml
  test/openshift/e2e/parallel/1-102_validate_handle_terminating_namespaces/04-assert.yaml
  test/openshift/e2e/parallel/1-102_validate_handle_terminating_namespaces/04-create-ns.yaml
  test/openshift/e2e/parallel/1-102_validate_handle_terminating_namespaces/05-assert.yaml
  test/openshift/e2e/parallel/1-102_validate_handle_terminating_namespaces/05-create-app.yaml
  test/openshift/e2e/parallel/1-102_validate_handle_terminating_namespaces/99-delete.yaml
  test/openshift/e2e/sequential/1-020_validate_redis_ha_nonha/01-assert.yaml
  test/openshift/e2e/sequential/1-020_validate_redis_ha_nonha/01-errors.yaml
  test/openshift/e2e/sequential/1-020_validate_redis_ha_nonha/02-assert.yaml
  test/openshift/e2e/sequential/1-020_validate_redis_ha_nonha/02-enable-ha.yaml
  test/openshift/e2e/sequential/1-020_validate_redis_ha_nonha/02-errors.yaml
  test/openshift/e2e/sequential/1-020_validate_redis_ha_nonha/03-assert.yaml
  test/openshift/e2e/sequential/1-020_validate_redis_ha_nonha/03-update-ha-resources.yaml
  test/openshift/e2e/sequential/1-020_validate_redis_ha_nonha/04-assert.yaml
  test/openshift/e2e/sequential/1-020_validate_redis_ha_nonha/04-disable-ha.yaml
  test/openshift/e2e/sequential/1-020_validate_redis_ha_nonha/04-errors.yaml
  test/openshift/e2e/sequential/1-071_validate_node_selectors/01-assert.yaml
  test/openshift/e2e/sequential/1-071_validate_node_selectors/02-assert.yaml
  test/openshift/e2e/sequential/1-071_validate_node_selectors/02-custom-node-selector.yaml
  test/openshift/e2e/sequential/1-071_validate_node_selectors/03-assert.yaml
  test/openshift/e2e/sequential/1-071_validate_node_selectors/03-patch-run-on-infra.yaml
  test/openshift/e2e/sequential/1-071_validate_node_selectors/04-change-back.yaml
  test/openshift/e2e/sequential/1-071_validate_node_selectors/04-errors.yaml
Labels: kind/enhancement, lgtm, approved, ok-to-test

#543 Update Kuttl tests for v1.8
  test/openshift/e2e/parallel/1-086_validate_applicationset_extra_command_args/01-assert.yaml
  test/openshift/e2e/parallel/1-086_validate_applicationset_extra_command_args/01-basic-argocd-install.yaml
  test/openshift/e2e/parallel/1-086_validate_applicationset_extra_command_args/02-add-extraCommandArgs.yaml
  test/openshift/e2e/parallel/1-086_validate_applicationset_extra_command_args/02-assert.yaml
  test/openshift/e2e/parallel/1-086_validate_applicationset_extra_command_args/99-delete.yaml
  test/openshift/e2e/parallel/1-088_validate_applicationset_add_env_vars/01-assert.yaml
  test/openshift/e2e/parallel/1-088_validate_applicationset_add_env_vars/01-basic-argocd-install.yaml
  test/openshift/e2e/parallel/1-088_validate_applicationset_add_env_vars/02-add-env-vars.yaml
  test/openshift/e2e/parallel/1-088_validate_applicationset_add_env_vars/02-assert.yaml
  test/openshift/e2e/parallel/1-089_validate_extra_repo_commands_args/01-assert.yaml
  test/openshift/e2e/parallel/1-089_validate_extra_repo_commands_args/01-basic-argocd-install.yaml
  test/openshift/e2e/parallel/1-089_validate_extra_repo_commands_args/02-add-extraRepoCommandArgs.yaml
  test/openshift/e2e/parallel/1-089_validate_extra_repo_commands_args/02-assert.yaml
  test/openshift/e2e/parallel/1-089_validate_extra_repo_commands_args/99-delete.yaml
  test/openshift/e2e/parallel/1-091_argocd_app_validate-applicationset-status/01-assert.yaml
  test/openshift/e2e/parallel/1-091_argocd_app_validate-applicationset-status/01-install.yaml
  test/openshift/e2e/parallel/1-091_argocd_app_validate-applicationset-status/02-assert.yaml
  test/openshift/e2e/parallel/1-091_argocd_app_validate-applicationset-status/02-enable-appset.yaml
  test/openshift/e2e/parallel/1-091_argocd_app_validate-applicationset-status/03-change-appset-image.yaml
  test/openshift/e2e/parallel/1-091_argocd_app_validate-applicationset-status/04-assert.yaml
  test/openshift/e2e/parallel/1-091_argocd_app_validate-applicationset-status/04-delete-exisiting-deployment.yaml
  test/openshift/e2e/parallel/1-092_validate_workload_status_monitoring_alert/01-assert.yaml
  test/openshift/e2e/parallel/1-092_validate_workload_status_monitoring_alert/01-install.yaml
  test/openshift/e2e/parallel/1-092_validate_workload_status_monitoring_alert/02-verify-alert.yaml
  test/openshift/e2e/parallel/1-092_validate_workload_status_monitoring_alert/03-disable-monitoring.yaml
  test/openshift/e2e/parallel/1-092_validate_workload_status_monitoring_alert/03-errors.yaml
  test/openshift/e2e/parallel/1-095_validate_dex_clientsecret/01-assert.yaml
  test/openshift/e2e/parallel/1-095_validate_dex_clientsecret/01-install.yaml
  test/openshift/e2e/parallel/1-095_validate_dex_clientsecret/02-check-clientSecret-cm.yaml
  test/openshift/e2e/parallel/1-095_validate_dex_clientsecret/03-verify-clientsecret-secret.yaml
  test/openshift/e2e/parallel/1-096-validate_home_env_argocd_controller/01-assert.yaml
  test/openshift/e2e/sequential/1-008_validate-4.9CI-Failures/01-assert.yaml
  test/openshift/e2e/sequential/1-008_validate-4.9CI-Failures/01-install.yaml
  test/openshift/e2e/sequential/1-008_validate-4.9CI-Failures/02-assert.yaml
  test/openshift/e2e/sequential/1-008_validate-4.9CI-Failures/02-create-rbac.yaml
  test/openshift/e2e/sequential/1-008_validate-4.9CI-Failures/03-assert.yaml
  test/openshift/e2e/sequential/1-008_validate-4.9CI-Failures/03-create-app.yaml
  test/openshift/e2e/sequential/1-071_validate_node_selectors/01-assert.yaml
  test/openshift/e2e/sequential/1-071_validate_node_selectors/02-assert.yaml
  test/openshift/e2e/sequential/1-071_validate_node_selectors/02-custom-node-selector.yaml
  test/openshift/e2e/sequential/1-071_validate_node_selectors/03-assert.yaml
  test/openshift/e2e/sequential/1-071_validate_node_selectors/03-patch-run-on-infra.yaml
  test/openshift/e2e/sequential/1-071_validate_node_selectors/04-change-back.yaml
  test/openshift/e2e/sequential/1-071_validate_node_selectors/04-errors.yaml
  test/openshift/e2e/sequential/1-077_validate_workload_status_monitoring_alert/02-verify-alert.yaml
Labels: lgtm, approved

#537 [v1.8] chore: Update argocd-operator to fix sso test failure
  go.mod
  go.sum
  test/openshift/e2e/sequential/1-050_validate_sso_config/01-assert.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/01-install.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/02-assert.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/02-errors.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/02-remove-spec-sso.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/03-add-spec-dex.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/03-assert.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/04-assert.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/04-disable-dex-through-sub.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/04-errors.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/05-assert.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/05-unset-disable-dex-env-var.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/06-errors.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/06-remove-spec-dex.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/07-assert.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/07-errors.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/07-provider-keycloak-dex-spec.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/08-assert.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/08-remove-spec-dex.yaml
Labels: kind/bug, lgtm, approved

#560 Cherry pick 1.9.1
  bundle/manifests/argoproj.io_applications.yaml
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/crd/bases/argoproj.io_applications.yaml
  config/manifests/patches/description.yaml
  go.mod
  go.sum
  test/openshift/e2e/ignore-tests/sequential/1-031_validate_toolchain/01-check.yaml
Labels: lgtm, approved

#574 Fixed log timestamp format
  go.mod
  main.go
Labels: kind/enhancement, lgtm, approved

#530 Fix: 1-042_validate_status_host test
  test/openshift/e2e/ignore-tests/sequential/1-042_validate_status_host/02-check_URL.yaml
  test/openshift/e2e/ignore-tests/sequential/1-042_validate_status_host/03-modify_route_URL.yaml
  test/openshift/e2e/ignore-tests/sequential/1-042_validate_status_host/05-check_URL_gone.yaml
  test/openshift/e2e/parallel/1-042_validate_status_host/01-assert.yaml
  test/openshift/e2e/parallel/1-042_validate_status_host/01-install.yaml
  test/openshift/e2e/parallel/1-042_validate_status_host/02-check_URL.yaml
  test/openshift/e2e/parallel/1-042_validate_status_host/03-assert.yaml
  test/openshift/e2e/parallel/1-042_validate_status_host/03-modify_route_URL.yaml
  test/openshift/e2e/parallel/1-042_validate_status_host/04-disable_route.yaml
  test/openshift/e2e/parallel/1-042_validate_status_host/04-errors.yaml
Labels: lgtm, approved

#559 GITOPS-2690 adding all the example used in testing from different sources
  test/examples/1-027_operand-from-git/argocd.yaml
  test/examples/1-027_operand-from-git/kustomization.yaml
  test/examples/1-027_operand-from-git/namespace.yaml
  test/examples/Readme.md
  test/examples/bgd-k8s/base/bgd-configmap.yaml
  test/examples/bgd-k8s/base/bgd-deployment.yaml
  test/examples/bgd-k8s/base/bgd-namespace.yaml
  test/examples/bgd-k8s/base/bgd-svc.yaml
  test/examples/bgd-k8s/base/kustomization.yaml
  test/examples/bgd-k8s/overlays/kind/bgd-ingress.yaml
  test/examples/bgd-k8s/overlays/kind/kustomization.yaml
  test/examples/bgd-k8s/overlays/mac/bgd-ingress.yaml
  test/examples/bgd-k8s/overlays/mac/kustomization.yaml
  test/examples/deploymentconfig-example/deploymentconfig.yaml
  test/examples/guestbook/guestbook-ui-deployment.yaml
  test/examples/guestbook/guestbook-ui-svc.yaml
  test/examples/kustomize-example/configmap.yaml
  test/examples/kustomize-example/kustomization.yaml
  test/examples/kustomize-example/kustomize-configmap.yaml
  test/examples/kustomize-guestbook/guestbook-ui-deployment.yaml
  test/examples/kustomize-guestbook/guestbook-ui-svc.yaml
  test/examples/kustomize-guestbook/kustomization.yaml
Labels: kind/enhancement, lgtm, approved

#545 Test: 1-035_validate_argocd_secret_repopulate
  test/openshift/e2e/ignore-tests/sequential/1-035_validate_argocd_secret_repopulate/03-check_secret_repopulate.yaml
  test/openshift/e2e/sequential/1-035_validate_argocd_secret_repopulate/01-assert.yaml
  test/openshift/e2e/sequential/1-035_validate_argocd_secret_repopulate/02-remove_secret_data.yaml
  test/openshift/e2e/sequential/1-035_validate_argocd_secret_repopulate/03-check_secret_repopulate.yaml
  test/openshift/e2e/sequential/1-035_validate_argocd_secret_repopulate/04-check_controller_pod_status.yaml
  test/openshift/e2e/sequential/1-035_validate_argocd_secret_repopulate/05-argocd_login.yaml
Labels: lgtm, approved

#573 update tests with examples from gitops-operator repo
  test/examples/deploymentconfig-example_replica_0/deploymentconfig.yaml
  test/openshift/e2e/parallel/1-054_validate_deploymentconfig/02-install-deploymentconfig.yaml
  test/openshift/e2e/parallel/1-054_validate_deploymentconfig/04-scaledown-deploymentconfig.yaml
  test/openshift/e2e/parallel/1-058_validate_prometheus_rule/03-create_application.yaml
  test/openshift/e2e/parallel/1-070_validate_config_management_plugin/02-create-app.yaml
  test/openshift/e2e/parallel/1-083_validate_kustomize_namereference/02-install-kustomize-app.yaml
  test/openshift/e2e/parallel/1-102_validate_handle_terminating_namespaces/05-create-app.yaml
Labels: kind/enhancement, lgtm, approved
