Repository redhat-developer/gitops-operator, pull requests merged in 2023-09, with the labels that each got.

#586 Fixed the default ArgoCD role for default instance openshift-gitops
  controllers/argocd/argocd.go
  controllers/argocd/argocd_test.go
  docs/OpenShift GitOps Usage Guide.md
  test/openshift/e2e/sequential/1-086_validate_default_argocd_role/01-assert.yaml
  test/openshift/e2e/sequential/1-086_validate_default_argocd_role/02-assert.yaml
  test/openshift/e2e/sequential/1-086_validate_default_argocd_role/02-install.yaml
Labels: lgtm, approved

#544 feat: Unify sso status & remove deprecated .spec.sso & .spec.dex fields
  bundle/manifests/argoproj.io_argocds.yaml
  config/crd/bases/argoproj.io_argocds.yaml
  controllers/gitopsservice_controller.go
  controllers/gitopsservice_controller_test.go
  docs/Migration_Guide.md
  docs/OpenShift GitOps Usage Guide.md
  go.mod
  go.sum
  hack/non-olm-install/README.md
  test/e2e/gitopsservice_test.go
  test/e2e/suite_test.go
  test/nondefaulte2e/suite_test.go
  test/openshift/e2e/parallel/1-052_validate_rolebinding_number/02-check_rolebindings.yaml
  test/openshift/e2e/parallel/1-070_validate_config_management_plugin/01-assert.yaml
  test/openshift/e2e/parallel/1-077_validate_disable_dex_removed/01-check_disable_dex_removed.yaml
  test/openshift/e2e/parallel/1-098_validate_dex_clientsecret/01-assert.yaml
  test/openshift/e2e/parallel/1-098_validate_dex_clientsecret/01-install.yaml
  test/openshift/e2e/parallel/1-098_validate_dex_clientsecret/02-verify-clientsecret.yaml
  test/openshift/e2e/sequential/1-050_validate_sso/01-assert.yaml
  test/openshift/e2e/sequential/1-050_validate_sso/01-install.yaml
  test/openshift/e2e/sequential/1-050_validate_sso/02-assert.yaml
  test/openshift/e2e/sequential/1-050_validate_sso/02-errors.yaml
  test/openshift/e2e/sequential/1-050_validate_sso/02-remove-spec-sso.yaml
  test/openshift/e2e/sequential/1-050_validate_sso/07-assert.yaml
  test/openshift/e2e/sequential/1-050_validate_sso/07-errors.yaml
  test/openshift/e2e/sequential/1-050_validate_sso/07-provider-keycloak-dex-spec.yaml
  test/openshift/e2e/sequential/1-050_validate_sso/08-assert.yaml
  test/openshift/e2e/sequential/1-050_validate_sso/08-remove-spec-dex.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/01-assert.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/03-assert.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/04-assert.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/04-disable-dex-through-sub.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/05-assert.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/05-unset-disable-dex-env-var.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/06-errors.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/06-remove-spec-dex.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/07-assert.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/08-assert.yaml
  test/openshift/e2e/sequential/1-076_validate_single_deprecation_notice/01-assert.yaml
  test/openshift/e2e/sequential/1-076_validate_single_deprecation_notice/01-install.yaml
  test/openshift/e2e/sequential/1-076_validate_single_deprecation_notice/02-count-occurrence.yaml
  test/openshift/e2e/sequential/1-076_validate_single_deprecation_notice/03-delete.yaml
  test/openshift/e2e/sequential/1-076_validate_single_deprecation_notice/03-errors.yaml
  test/openshift/e2e/sequential/1-076_validate_single_deprecation_notice/04-assert.yaml
  test/openshift/e2e/sequential/1-076_validate_single_deprecation_notice/04-install.yaml
  test/openshift/e2e/sequential/1-076_validate_single_deprecation_notice/05-count-occurrence.yaml
  test/openshift/e2e/sequential/1-076_validate_single_deprecation_notice/99-delete.yaml
Labels: kind/enhancement, lgtm, approved

#596 add documentation for gitops monitoring dashboards
  docs/OpenShift GitOps Usage Guide.md
  docs/assets/39.gitops_monitoring_dashboards_dropdown.png
Labels: lgtm, approved

#595 Change installation namespace
  test/openshift/e2e/ignore-tests/sequential/1-083_validate_apps_in_any_namespace/01-assert.yaml
  test/openshift/e2e/ignore-tests/sequential/1-083_validate_apps_in_any_namespace/02-assert.yaml
  test/openshift/e2e/ignore-tests/sequential/1-083_validate_apps_in_any_namespace/06-assert.yaml
  test/openshift/e2e/parallel/1-090_validate_permissions/01-assert.yaml
Labels: lgtm, approved

#594 feat: Upgrade ArgoCD CRD to v1beta1 & add conversion webhook support
  Makefile
  bundle/manifests/argoproj.io_argocds.yaml
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  bundle/manifests/openshift-gitops-operator-webhook-service_v1_service.yaml
  config/crd/bases/argoproj.io_argocds.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_argocds.yaml
  config/crd/patches/webhook_in_argocds.yaml
  config/default/kustomization.yaml
  config/default/manager_webhook_patch.yaml
  config/manifests/kustomization.yaml
  config/samples/argoproj.io_v1beta1_argocd.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/service.yaml
  controllers/argocd/argocd.go
  controllers/argocd/argocd_test.go
  controllers/argocd/openshift/clusterconfig_test.go
  controllers/argocd/openshift/openshift.go
  controllers/argocd_metrics_controller.go
  controllers/argocd_metrics_controller_test.go
  controllers/gitopsservice_controller.go
  controllers/gitopsservice_controller_test.go
  docs/OpenShift GitOps Usage Guide.md
  go.mod
  go.sum
  main.go
  test/e2e/gitopsservice_test.go
  test/e2e/suite_test.go
  test/helper/application_status.go
  test/nondefaulte2e/gitops_service_nondefault_test.go
  test/nondefaulte2e/suite_test.go
  test/openshift/e2e/parallel/1-073_validate_rhsso/01-assert.yaml
  test/openshift/e2e/parallel/1-103_argocd_alpha_to_beta_conversion/01-alpha_argocd.yaml
  test/openshift/e2e/parallel/1-103_argocd_alpha_to_beta_conversion/01-assert.yaml
  test/openshift/e2e/parallel/1-103_argocd_alpha_to_beta_conversion/02-delete.yaml
  test/openshift/e2e/parallel/1-103_argocd_alpha_to_beta_conversion/02-errors.yaml
Labels: kind/enhancement, lgtm, approved

#599 feat: Add tls cert mount for appset controller
  bundle/manifests/argoproj.io_argocds.yaml
  config/crd/bases/argoproj.io_argocds.yaml
  go.mod
  go.sum
  test/openshift/e2e/parallel/1-104_validate_applicationset_tls_scm_volume_mount/01-assert.yaml
  test/openshift/e2e/parallel/1-104_validate_applicationset_tls_scm_volume_mount/01-install.yaml
Labels: kind/enhancement, lgtm, approved

#600 feat: update application and applicationsets crds to match with argo cd v2.8.3
  bundle/manifests/argoproj.io_applications.yaml
  bundle/manifests/argoproj.io_applicationsets.yaml
  config/crd/bases/argoproj.io_applications.yaml
  config/crd/bases/argoproj.io_applicationsets.yaml
Labels: lgtm

#588 test: Avoid displaying argocd-secret in the test log
  test/openshift/e2e/sequential/1-035_validate_argocd_secret_repopulate/03-check_secret_repopulate.yaml
Labels: lgtm, approved

#580 update 1-031 to check for parallel component version fixes:2641
  test/openshift/e2e/ignore-tests/sequential/1-031_validate_toolchain/01-check.yaml
  test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml
Labels: lgtm, approved, kind/failing-test

#597 fix: fix non-olm sso test and use set for env variable
  test/openshift/e2e/ignore-tests/sequential/1-018_validate_disable_default_instance/02-patch-subscription.yaml
  test/openshift/e2e/ignore-tests/sequential/1-018_validate_disable_default_instance/04-patch-subscription.yaml
  test/openshift/e2e/sequential/1-034_validate_custom_roles/02-patch-subscription.yaml
  test/openshift/e2e/sequential/1-034_validate_custom_roles/06-revert-patch.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/04-disable-dex-through-sub.yaml
  test/openshift/e2e/sequential/1-050_validate_sso_config/05-unset-disable-dex-env-var.yaml
  test/openshift/e2e/sequential/1-056_validate_managed-by/04-add_env.yaml
  test/openshift/e2e/sequential/1-056_validate_managed-by/08-remove_env.yaml
  test/openshift/e2e/sequential/1-078_validate_default_argocd_consoleLink/02-add_env.yaml
  test/openshift/e2e/sequential/1-078_validate_default_argocd_consoleLink/04-disable-env.yaml
  test/openshift/e2e/sequential/1-078_validate_default_argocd_consoleLink/06-empty-valued-env.yaml
  test/openshift/e2e/sequential/1-078_validate_default_argocd_consoleLink/08-remove-env.yaml
Labels: lgtm, approved

#601 Updated default version to 1.9.2 and tools kustomize, regctl, yq
  hack/non-olm-install/install-gitops-operator.sh
Labels: kind/bug, lgtm, approved

#602 automatically enable openshift-ci on specific branch whenever it is created
  .github/workflow/openshift-ci-automation.yaml
Labels: kind/enhancement, lgtm, approved

#603 feat: Update non-olm-install script to setup conversion webhook
  config/rbac/kustomization.yaml
  hack/non-olm-install/README.md
  hack/non-olm-install/install-gitops-operator.sh
Labels: kind/enhancement, lgtm, approved

#605 fix: issues with kam image reconcile and pull latest argocd-operator
  controllers/kam.go
  go.mod
  go.sum
Labels: lgtm
