Repository redhat-developer/gitops-operator, pull requests merged in 2024-01, with the labels that each got.

#637 Remove 1-020_validate_redis_ha_nonha from periodic runs
  test/openshift/e2e/ignore-tests/sequential/1-020_validate_redis_ha_nonha/01-assert.yaml
  test/openshift/e2e/ignore-tests/sequential/1-020_validate_redis_ha_nonha/01-errors.yaml
  test/openshift/e2e/ignore-tests/sequential/1-020_validate_redis_ha_nonha/02-assert.yaml
  test/openshift/e2e/ignore-tests/sequential/1-020_validate_redis_ha_nonha/02-enable-ha.yaml
  test/openshift/e2e/ignore-tests/sequential/1-020_validate_redis_ha_nonha/02-errors.yaml
  test/openshift/e2e/ignore-tests/sequential/1-020_validate_redis_ha_nonha/03-assert.yaml
  test/openshift/e2e/ignore-tests/sequential/1-020_validate_redis_ha_nonha/03-update-ha-resources.yaml
  test/openshift/e2e/ignore-tests/sequential/1-020_validate_redis_ha_nonha/04-assert.yaml
  test/openshift/e2e/ignore-tests/sequential/1-020_validate_redis_ha_nonha/04-disable-ha.yaml
  test/openshift/e2e/ignore-tests/sequential/1-020_validate_redis_ha_nonha/04-errors.yaml
Labels: lgtm, approved, kind/failing-test

#623 doc: Added secret management documentation
  docs/Integrate GitOps with Secrets Management.md
  docs/OpenShift GitOps Usage Guide.md
Labels: kind/documentation, lgtm, approved

#628 doc: Update SSO doc with latest information
  docs/OpenShift GitOps Usage Guide.md
  docs/dex_config_guidance.md
  docs/rhsso_config_guidance.md
Labels: kind/documentation

#639 add documentation for applicationSets
  docs/OpenShift GitOps Usage Guide.md
Labels: lgtm, approved

#643 fix github workflow dir name
  .github/workflows/openshift-ci-automation.yaml
Labels: kind/bug, lgtm

#631 Revert "Add GCP cherry pick bot"
  .github/cherry-pick-bot.yml
Labels: lgtm, approved

#604 feat: add script for installing nightly olm operator
  hack/scripts/olm-nightly-install.sh
Labels: kind/enhancement, lgtm, approved

#646 fix: argocd cve fix 2.8.9 for 0.8.0 operator
  go.mod
  go.sum
Labels: lgtm, approved

#648 fix: argocd upgrade for cve fix for 0.7.1 operator
  go.mod
  go.sum
Labels: lgtm, approved

#647 fix: argocd cve fix 2.9.5 for 0.9.0 operator
  go.mod
  go.sum
Labels: lgtm, approved

#649 update indirect argocd dependency
  go.mod
  go.sum
Labels: lgtm, approved
