Repository redhat-developer/gitops-operator, pull requests merged in 2024-08, with the labels that each got.

#757 Update to latest commit of argo-rollouts-manager 'a96aa79b546433ee2d68f48d424baaabed0cb2ac'
  bundle/manifests/argoproj.io_rolloutmanagers.yaml
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/crd/bases/argoproj.io_rolloutmanagers.yaml
  go.mod
  go.sum
  scripts/run-rollouts-e2e-tests.sh
Labels: lgtm

#758 feat: add support for sidecar container in controller and server
  Makefile
  bundle/manifests/argoproj.io_argocds.yaml
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/crd/bases/argoproj.io_argocds.yaml
  go.mod
  go.sum
  test/openshift/e2e/parallel/1-019_validate_volume_mounts/01-assert.yaml
  test/openshift/e2e/parallel/1-019_validate_volume_mounts/01-install.yaml
  test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml
  test/openshift/e2e/parallel/1-106_validate_appcontroller_initcontainers/01-assert.yaml
  test/openshift/e2e/parallel/1-106_validate_appcontroller_initcontainers/01-install.yaml
  test/openshift/e2e/parallel/1-107_validate_server_initcontainers/01-assert.yaml
  test/openshift/e2e/parallel/1-107_validate_server_initcontainers/01-install.yaml
  test/openshift/e2e/parallel/1-108_validate_appcontroller_sidecar/01-assert.yaml
  test/openshift/e2e/parallel/1-108_validate_appcontroller_sidecar/01-install.yaml
  test/openshift/e2e/parallel/1-109_validate_server_sidecar/01-assert.yaml
  test/openshift/e2e/parallel/1-109_validate_server_sidecar/01-install.yaml
Labels: lgtm, approved

#740 Fix bug where ArgoCD removes nodePlacement stanza from configuration
  controllers/argocd_metrics_controller_test.go
  controllers/gitopsservice_controller.go
  controllers/gitopsservice_controller_test.go
Labels: kind/bug

#756 Add dashboard for Rollouts
  controllers/dashboards/gitops-rollouts.json
  docs/OpenShift GitOps Usage Guide.md
Labels: kind/enhancement, lgtm, ok-to-test

#766 Upgrade Argo CD Operator to pick up TLS race cond fix
  go.mod
  go.sum
Labels: kind/bug

#767 chore: update to latest argocd-operator for 1.14 release
  bundle/manifests/argoproj.io_applications.yaml
  bundle/manifests/argoproj.io_applicationsets.yaml
  bundle/manifests/argoproj.io_appprojects.yaml
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/crd/bases/argoproj.io_applications.yaml
  config/crd/bases/argoproj.io_applicationsets.yaml
  config/crd/bases/argoproj.io_appprojects.yaml
  config/crd/bases/argoproj.io_argocds.yaml
  config/crd/bases/argoproj.io_notificationsconfigurations.yaml
  go.mod
  go.sum
  openshift-gitops-e2e.json
  test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml
Labels: lgtm, approved

#765 feat: remove kam resources from operator
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/manifests/bases/gitops-operator.clusterserviceversion.yaml
  config/manifests/patches/description.yaml
  controllers/consoleplugin.go
  controllers/gitopsservice_controller.go
  controllers/gitopsservice_controller_test.go
  controllers/kam.go
  docs/OpenShift GitOps Usage Guide.md
  hack/non-olm-install/README.md
  hack/non-olm-install/install-gitops-operator.sh
  scripts/openshift-CI-kuttl-tests.sh
  scripts/openshift-interop-kuttl-tests.sh
  test/e2e/gitopsservice_test.go
  test/nondefaulte2e/gitops_service_nondefault_test.go
  test/openshift/e2e/ignore-tests/parallel/1-090_validate_permissions/01-assert.yaml
  test/openshift/e2e/ignore-tests/sequential/1-001_validate_kam_service/01-assert.yaml
  test/openshift/e2e/ignore-tests/sequential/1-001_validate_kam_service/01-check-kam-service.yaml
  test/openshift/e2e/ignore-tests/sequential/1-001_validate_kam_service/02-check-route.yaml
  test/openshift/e2e/ignore-tests/sequential/1-001_validate_kam_service/03-check-download.yaml
  test/openshift/e2e/ignore-tests/sequential/1-018_validate_disable_default_instance/01-assert.yaml
  test/openshift/e2e/ignore-tests/sequential/1-028_validate_run_on_infra/01-assert.yaml
  test/openshift/e2e/ignore-tests/sequential/1-028_validate_run_on_infra/errors.yaml
  test/openshift/e2e/ignore-tests/sequential/1-071_validate_node_selectors/01-assert.yaml
  test/openshift/e2e/ignore-tests/sequential/1-071_validate_node_selectors/02-assert.yaml
  test/openshift/e2e/ignore-tests/sequential/1-071_validate_node_selectors/03-assert.yaml
  test/openshift/e2e/ignore-tests/sequential/1-071_validate_node_selectors/04-errors.yaml
  test/openshift/e2e/sequential/1-001_validate_kam_service/01-assert.yaml
  test/openshift/e2e/sequential/1-001_validate_kam_service/01-check-kam-service.yaml
  test/openshift/e2e/sequential/1-001_validate_kam_service/02-check-route.yaml
  test/openshift/e2e/sequential/1-001_validate_kam_service/03-check-download.yaml
  test/openshift/e2e/sequential/1-028_validate_run_on_infra/01-assert.yaml
  test/openshift/e2e/sequential/1-028_validate_run_on_infra/errors.yaml
  test/openshift/e2e/sequential/1-071_validate_node_selectors/01-assert.yaml
  test/openshift/e2e/sequential/1-071_validate_node_selectors/02-assert.yaml
  test/openshift/e2e/sequential/1-071_validate_node_selectors/03-assert.yaml
  test/openshift/e2e/sequential/1-071_validate_node_selectors/04-errors.yaml
Labels: lgtm, approved

#772 chore: update argocd to 2.12.3
  go.mod
  go.sum
  test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml
Labels: lgtm, approved

#773 chore: update to latest argo
  go.mod
  go.sum
  test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml
Labels: lgtm, approved

#763 Enable e2e tests
  test/e2e/suite_test.go
  test/nondefaulte2e/suite_test.go
Labels: lgtm, approved
