Repository redhat-developer/gitops-operator, pull requests merged in 2024-04, with the labels that each got.

#671 chore: Update argocd-operator to 1.10.1-rc to address CVEs
  bundle/manifests/argoproj.io_applicationsets.yaml
  config/crd/bases/argoproj.io_applicationsets.yaml
  go.mod
  go.sum
  test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml
Labels: kind/bug

#672 Update argocd-operator
  go.mod
  go.sum
  test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml
Labels: kind/bug, lgtm, approved

#673 Update argocd-operator
  bundle/manifests/argoproj.io_applicationsets.yaml
  bundle/manifests/argoproj.io_argocds.yaml
  config/crd/bases/argoproj.io_applicationsets.yaml
  config/crd/bases/argoproj.io_argocds.yaml
  go.mod
  go.sum
Labels: kind/bug, lgtm, approved

#679 fix: enable infra label to console-plugin deployment
  controllers/consoleplugin.go
  controllers/consoleplugin_test.go
Labels: lgtm

#678 Removed duplicate CRD entry for ArgoCD, updated missing details for operator owned crds
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/manifests/bases/gitops-operator.clusterserviceversion.yaml
Labels: lgtm

#684 fix: upgrade argocd-operator-0.9
  go.mod
  go.sum
Labels: lgtm

#687 Fixed CRDs owned by GitOps Operator in the clusterserviceversion mani…
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/manifests/bases/gitops-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#686 Fixed CRDs owned by GitOps Operator in the clusterserviceversion manifest file for v1.11
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/manifests/bases/gitops-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#691 fix: notifications controller does not handle context
  bundle/manifests/argoproj.io_notificationsconfigurations.yaml
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/crd/bases/argoproj.io_notificationsconfigurations.yaml
  config/manifests/bases/gitops-operator.clusterserviceversion.yaml
  go.mod
  go.sum
Labels: lgtm

#688 Update to latest commit of argo-rollouts-manager 'efd9a78591b8be58cd65529dbd624306590911b0'
  bundle/manifests/argoproj.io_rolloutmanagers.yaml
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/crd/bases/argoproj.io_rolloutmanagers.yaml
  config/manifests/bases/gitops-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  scripts/openshiftci-presubmit-all-tests.sh
Labels: lgtm, approved
