Repository redhat-developer/gitops-operator, pull requests merged in 2024-10, with the labels that each got.

#783 fix: Remove resource limits for manager container
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: kind/bug, lgtm, approved

#786 Upgrade gitops-operator v1.13 to Argo Rollouts operator v0.0.3.1
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  go.mod
  go.sum
  hack/non-olm-install/install-gitops-operator.sh
  test/openshift/e2e/sequential/1-100_validate_rollouts_resources_creation/01-assert.yaml
  test/openshift/e2e/sequential/1-100_validate_rollouts_resources_creation/01-install-rolloutmanager.yaml
  test/openshift/e2e/sequential/1-100_validate_rollouts_resources_creation/02-assert.yaml
  test/openshift/e2e/sequential/1-101_validate_rollout_policyrules/01-install-rollloutmanager.yaml
Labels: lgtm

#787 update argocd-operator version
  go.mod
  go.sum
  test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml
Labels: lgtm, approved

#789 Update argocd operator 1.13.2
  go.mod
  go.sum
  test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml
Labels: lgtm, kind/cleanup

#792 Upgrade v1.14 to Argo Rollouts manager v0.0.4.1: df262fe66d25638de47ee98130dcebe016c8fae5
  go.mod
  go.sum
Labels: kind/bug, lgtm, approved

#793 Upgrade v1.13 to Argo Rollouts manager v0.0.3.1: e054d35fd0d9dad6b9ae26efa60f43cadc…
  go.mod
  go.sum
Labels: kind/bug, lgtm, approved

#788 update argocd-operator for v1.12
  go.mod
  go.sum
  test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml
Labels: lgtm, approved, kind/cleanup

#794 Update tests in v1.12
  test/openshift/e2e/parallel/1-066_validate_redis_secure_comm_no_autotls_no_ha/05-check_deployments.yaml
  test/openshift/e2e/parallel/1-090_validate_permissions/01-assert.yaml
Labels: lgtm, approved, kind/failing-test

#798 update argocd-operator version for release 1.14.1
  go.mod
  go.sum
  test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml
Labels: lgtm

#796 update argocd-operator version for 1.12.6 release
  go.mod
  go.sum
  test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml
Labels: lgtm, kind/cleanup

#797 update argocd-operator version for release 1.13.2
  go.mod
  go.sum
  test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml
Labels: lgtm, approved, kind/cleanup

#795 Rollouts E2E test script should point to v0.0.4.1 branch
  scripts/run-rollouts-e2e-tests.sh
Labels: kind/bug

#799 Update to latest commit of argo-rollouts-manager '85db81b64541a2e0f10616acca8b24ac63f46b42'
  bundle/manifests/argoproj.io_rolloutmanagers.yaml
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/crd/bases/argoproj.io_rolloutmanagers.yaml
  go.mod
  go.sum
  scripts/run-rollouts-e2e-tests.sh
Labels: lgtm, approved

#800 Fix typo in YAML for 1-020_validate_redis_ha_nonha
  test/openshift/e2e/sequential/1-020_validate_redis_ha_nonha/04-disable-ha.yaml
Labels: kind/bug, lgtm, approved
