Repository redhat-developer/gitops-operator, pull requests merged in 2024-07, with the labels that each got.

#743 Changing registry image to fix CI failure
  openshift-ci/build-root/Dockerfile
Labels: lgtm, approved, kind/failing-test

#705 chore: Add Siddhesh Ghadi in approvers list
  OWNERS
Labels: lgtm, approved

#742 chore: update operator-sdk version to 1.32
  Makefile
  bundle.Dockerfile
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  bundle/manifests/openshift-gitops-operator-metrics-service_v1_service.yaml
  bundle/metadata/annotations.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
  config/rbac/auth_proxy_service.yaml
  test/e2e/suite_test.go
  test/nondefaulte2e/suite_test.go
Labels: lgtm, approved, kind/cleanup

#748 chore: upgrade operator-sdk to 1.35
  Dockerfile
  Makefile
  PROJECT
  bundle.Dockerfile
  bundle/manifests/argoproj.io_argocds.yaml
  bundle/manifests/argoproj.io_notificationsconfigurations.yaml
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  cmd/main.go
  config/crd/bases/argoproj.io_argocds.yaml
  config/crd/bases/argoproj.io_notificationsconfigurations.yaml
  go.mod
  go.sum
  openshift-ci/build-root/Dockerfile
Labels: lgtm, approved, kind/cleanup

#747 Minor fixes to update-rollouts-manager script
  hack/upgrade-rollouts-manager/README.md
  hack/upgrade-rollouts-manager/main.go
Labels: kind/enhancement, lgtm

#738 Add a GitHub check to ensure consistency of generated manifests
  .github/workflows/codegen.yaml
Labels: kind/enhancement

#746 Update to latest commit of argo-rollouts-manager '192dd2c3b5dd026e2c59c5765e98ca2f70ca01f9'
  bundle/manifests/argoproj.io_analysisruns.yaml
  bundle/manifests/argoproj.io_analysistemplates.yaml
  bundle/manifests/argoproj.io_clusteranalysistemplates.yaml
  bundle/manifests/argoproj.io_experiments.yaml
  bundle/manifests/argoproj.io_rolloutmanagers.yaml
  bundle/manifests/argoproj.io_rollouts.yaml
  config/crd/bases/analysis-run-crd.yaml
  config/crd/bases/analysis-template-crd.yaml
  config/crd/bases/argoproj.io_rolloutmanagers.yaml
  config/crd/bases/cluster-analysis-template-crd.yaml
  config/crd/bases/experiment-crd.yaml
  config/crd/bases/rollout-crd.yaml
  go.mod
  go.sum
  scripts/run-rollouts-e2e-tests.sh
  test/openshift/e2e/sequential/1-101_validate_rollout_policyrules/01-assert.yaml
Labels: lgtm

#737 Add OpenShift Rollouts Route Plugin E2E tests to GitOps Operator tests
  scripts/run-rollouts-e2e-tests.sh
Labels: lgtm

#633 doc: Update & reorganize new argocd instance creation doc
  docs/OpenShift GitOps Usage Guide.md
Labels: kind/documentation, lgtm, approved

#754 Update test image for working with OCP 4.16
  openshift-ci/build-root/Dockerfile
Labels: kind/enhancement, lgtm, approved
