Repository redhat-developer/gitops-operator, pull requests merged in 2024-06, with the labels that each got.

#721 chore: Update argocd version and manifests
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/argoproj.io_applications.yaml
  bundle/manifests/argoproj.io_applicationsets.yaml
  bundle/manifests/argoproj.io_rollouts.yaml
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  bundle/manifests/pipelines.openshift.io_gitopsservices.yaml
  config/crd/bases/argoproj.io_applications.yaml
  config/crd/bases/argoproj.io_applicationsets.yaml
  config/crd/bases/argoproj.io_argocds.yaml
  config/crd/bases/pipelines.openshift.io_gitopsservices.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml
Labels: lgtm, approved

#723 Add script to run Rollouts tests against gitops-operator repo
  hack/upgrade-rollouts-manager/main.go
  scripts/run-rollouts-e2e-tests.sh
Labels: lgtm

#728 Include PR #1401 from argocd-operator
  go.mod
  go.sum
Labels: kind/bug

#727 Include PR #1401 from argocd-operator
  go.mod
  go.sum
Labels: kind/bug

#726 Replace argocd-operator v0.10.1-rc4 with commit SHA
  go.mod
  go.sum
Labels: kind/bug, lgtm, approved

#733 Update argocd operator to use released version 0.11.0
  go.mod
  go.sum
Labels: lgtm, approved

#735 Fix Rollouts plugin location URL format (v1.13)
  main.go
Labels: kind/bug, lgtm, approved

#722 Move operator-sdk target version to env var in Makefile, remove unused scripts
  Makefile
  scripts/install-operator-sdk.sh
  scripts/openshiftci-presubmit-all-tests.sh
Labels: lgtm

#729 Fix 'Unable to retrieve current OCP version: Malformed version' when running unit tests
  controllers/argocd_metrics_controller.go
Labels: lgtm, kind/failing-test

#736 'run-rollouts-e2e-tests.sh' should fail outright when an individual test fails
  scripts/run-rollouts-e2e-tests.sh
Labels: kind/bug, lgtm

#666 doc: fix small typos in README and dex doc
  README.md
  docs/dex_config_guidance.md
Labels: kind/documentation, lgtm, ok-to-test
