Repository redhat-developer/gitops-operator, pull requests merged in 2024-05, with the labels that each got.

#692 fix: upgrade to argo 2.8.18
  go.mod
  go.sum
Labels: lgtm, approved

#693 fix: upgrade to argo 2.10.9
  go.mod
  go.sum
  test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml
Labels: lgtm, approved

#695 fix: upgrade argocd to 2.9.14
  go.mod
  go.sum
  test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml
Labels: lgtm, approved

#696 Fix Kuttl E2E tests: Switch Rollouts tests to sequential, change Role to ClusterRole
  test/openshift/e2e/sequential/1-100_validate_rollouts_resources_creation/01-assert.yaml
  test/openshift/e2e/sequential/1-100_validate_rollouts_resources_creation/01-install-rolloutmanager.yaml
  test/openshift/e2e/sequential/1-100_validate_rollouts_resources_creation/02-assert.yaml
  test/openshift/e2e/sequential/1-101_validate_rollout_policyrules/01-assert.yaml
  test/openshift/e2e/sequential/1-101_validate_rollout_policyrules/01-install-rollloutmanager.yaml
Labels: kind/failing-test

#699 fix: add apiservicedefinitions for rollouts API [1.10]
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/manifests/bases/gitops-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/gitopsservice_controller.go
Labels: lgtm, approved

#689 Remove workaround from e2e tests for cluster config change related to issue #148
  test/e2e/gitopsservice_test.go
Labels: ok-to-test

#708 feat: secure redis authentication
  build/redis/haproxy.cfg.tpl
  build/redis/haproxy_init.sh.tpl
  build/redis/init.sh.tpl
  build/redis/redis.conf.tpl
  build/redis/redis_liveness.sh.tpl
  build/redis/redis_readiness.sh.tpl
  build/redis/sentinel.conf.tpl
  build/redis/sentinel_liveness.sh.tpl
  go.mod
  go.sum
Labels: lgtm

#709 feat: secure redis authentication
  build/redis/haproxy.cfg.tpl
  build/redis/haproxy_init.sh.tpl
  build/redis/init.sh.tpl
  build/redis/redis.conf.tpl
  build/redis/redis_liveness.sh.tpl
  build/redis/redis_readiness.sh.tpl
  build/redis/sentinel.conf.tpl
  build/redis/sentinel_liveness.sh.tpl
  go.mod
  go.sum
Labels: lgtm

#715 fix: sentinal liveliness issue
  build/redis/sentinel_liveness.sh.tpl
Labels: lgtm

#716 fix: sentinal liveliness issue
  build/redis/sentinel_liveness.sh.tpl
Labels: lgtm

#717 fix: sentinal liveliness issue
  build/redis/sentinel_liveness.sh.tpl
Labels: lgtm

#701 Script to auto-upgrade argo-rollouts-manager to latest
  hack/upgrade-rollouts-manager/.gitignore
  hack/upgrade-rollouts-manager/README.md
  hack/upgrade-rollouts-manager/go-run.sh
  hack/upgrade-rollouts-manager/go.mod
  hack/upgrade-rollouts-manager/go.sum
  hack/upgrade-rollouts-manager/init-repo.sh
  hack/upgrade-rollouts-manager/main.go
  hack/upgrade-rollouts-manager/settings_template.env
Labels: kind/enhancement, lgtm

#704 Add description label to ArgoCDSyncAlert
  controllers/argocd_metrics_controller.go
  controllers/argocd_metrics_controller_test.go
  test/openshift/e2e/ignore-tests/sequential/1-005_validate_metrics/01-assert.yaml
  test/openshift/e2e/ignore-tests/sequential/1-041_validate_argocd_sync_alert/01-assert.yaml
  test/openshift/e2e/sequential/1-041_validate_argocd_sync_alert/01-assert.yaml
Labels: ok-to-test

#719 feat: secure redis authentication
  api/v1alpha1/zz_generated.deepcopy.go
  build/redis/haproxy.cfg.tpl
  build/redis/haproxy_init.sh.tpl
  build/redis/init.sh.tpl
  build/redis/redis.conf.tpl
  build/redis/redis_liveness.sh.tpl
  build/redis/redis_readiness.sh.tpl
  build/redis/sentinel.conf.tpl
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/gitopsservice_controller.go
  test/openshift/e2e/ignore-tests/parallel/1-090_validate_permissions/01-assert.yaml
  test/openshift/e2e/parallel/1-066_validate_redis_secure_comm_no_autotls_no_ha/05-check_deployments.yaml
Labels: lgtm, approved

#658 chore: New infrastructure annotation format to improve the presence of metadata
  bundle/manifests/argoproj.io_rollouts.yaml
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/manifests/bases/gitops-operator.clusterserviceversion.yaml
  config/samples/argoproj.io_v1beta1_argocd.yaml
  config/samples/kustomization.yaml
Labels: lgtm, approved

#702 feat: make metrics scraping optional
  controllers/argocd_metrics_controller.go
  controllers/argocd_metrics_controller_test.go
  test/openshift/e2e/sequential/1-106_validate_argocd_metrics_controller/01-assert.yaml
  test/openshift/e2e/sequential/1-106_validate_argocd_metrics_controller/02-disable-metrics.yaml
  test/openshift/e2e/sequential/1-106_validate_argocd_metrics_controller/02-errors.yaml
  test/openshift/e2e/sequential/1-106_validate_argocd_metrics_controller/03-assert.yaml
  test/openshift/e2e/sequential/1-106_validate_argocd_metrics_controller/03-enable-metrics.yaml
Labels: lgtm, approved

#674 PSA: add restricted labels to openshift-gitops namespace
  controllers/gitopsservice_controller.go
Labels: kind/enhancement, lgtm, approved, ok-to-test
