Repository redhat-developer/gitops-operator, pull requests merged in 2024-11, with the labels that each got.

#780 feat: Support use of secrets for Route tls data
  bundle/manifests/argoproj.io_argocds.yaml
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/crd/bases/argoproj.io_argocds.yaml
  go.mod
  go.sum
  test/openshift/e2e/parallel/1-005_validate_route_tls/01-assert.yaml
  test/openshift/e2e/parallel/1-005_validate_route_tls/01-install.yaml
  test/openshift/e2e/parallel/1-005_validate_route_tls/02-assert.yaml
  test/openshift/e2e/parallel/1-005_validate_route_tls/02-embedded-tls-data.yaml
  test/openshift/e2e/parallel/1-005_validate_route_tls/03-assert.yaml
  test/openshift/e2e/parallel/1-005_validate_route_tls/03-secret-tls-data.yaml
  test/openshift/e2e/parallel/1-005_validate_route_tls/04-assert.yaml
  test/openshift/e2e/parallel/1-005_validate_route_tls/04-update-secret-tls-data.yaml
Labels: lgtm, approved

#803 chore: Upgrade argocd-operator versions
  bundle/manifests/argoproj.io_applications.yaml
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/crd/bases/argoproj.io_applications.yaml
  go.mod
  go.sum
  test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml
Labels: lgtm, approved

#805 chore: Upgrade argocd-operator versions v0.11.2
  bundle/manifests/argoproj.io_applications.yaml
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/crd/bases/argoproj.io_applications.yaml
  go.mod
  go.sum
  test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml
Labels: lgtm

#804 chore: Bump go to 1.22
  .ci-operator.yaml
  Dockerfile
  go.mod
  openshift-ci/build-root/Dockerfile
  test/openshift/e2e/ignore-tests/parallel/1-066_validate_redis_secure_comm_no_autotls_no_ha/02-generate_cert.yaml
  test/openshift/e2e/ignore-tests/parallel/1-067_validate_redis_secure_comm_no_autotls_ha/02-generate_cert.yaml
  test/openshift/e2e/parallel/1-066_validate_redis_secure_comm_no_autotls_no_ha/02-generate_cert.yaml
  test/openshift/e2e/parallel/1-067_validate_redis_secure_comm_no_autotls_ha/02-generate_cert.yaml
Labels: lgtm, approved

#806 update crd and argocd-operator with master for downstream rollout UI extension
  bundle/manifests/argoproj.io_argocds.yaml
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/crd/bases/argoproj.io_argocds.yaml
  go.mod
  go.sum
Labels: kind/enhancement, lgtm

#811 chore: Upgrade argocd
  bundle/manifests/argoproj.io_applications.yaml
  bundle/manifests/argoproj.io_applicationsets.yaml
  bundle/manifests/argoproj.io_appprojects.yaml
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/crd/bases/argoproj.io_applications.yaml
  config/crd/bases/argoproj.io_applicationsets.yaml
  config/crd/bases/argoproj.io_appprojects.yaml
  config/crd/bases/argoproj.io_argocds.yaml
  config/crd/bases/argoproj.io_notificationsconfigurations.yaml
  go.mod
  go.sum
  test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml
Labels: lgtm, approved

#810 chore: Upgrade argocd-operator versions v0.13.0
  bundle/manifests/argoproj.io_applications.yaml
  bundle/manifests/argoproj.io_applicationsets.yaml
  bundle/manifests/argoproj.io_appprojects.yaml
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/crd/bases/argoproj.io_applications.yaml
  config/crd/bases/argoproj.io_applicationsets.yaml
  config/crd/bases/argoproj.io_appprojects.yaml
  config/crd/bases/argoproj.io_argocds.yaml
  config/crd/bases/argoproj.io_notificationsconfigurations.yaml
  go.mod
  go.sum
  test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml
Labels: lgtm, approved, ok-to-test

#813 chore: Upgrade argo rollout manager
  go.mod
  go.sum
Labels: lgtm, approved

#808 Create downstream container image for konflux
  .tekton/gitops-operator-pull-request.yaml
  .tekton/gitops-operator-push.yaml
  Containerfile.plugin
Labels: kind/enhancement, lgtm, approved
