Repository redhat-developer/gitops-operator, pull requests merged in 2025-06, with the labels that each got.

#900 fix(backport): add security context to plugin deployment
  controllers/consoleplugin.go
  controllers/consoleplugin_test.go
Labels: kind/bug

#907 Add Ginkgo test instructions via README.md
  test/openshift/e2e/README.md
Labels: kind/documentation

#910 Update to latest commit of argo-rollouts-manager 'ebd6207c8bb1352eac450307573fdb0dbd5e7bd0'
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  scripts/run-rollouts-e2e-tests.sh
Labels: lgtm, approved
