Repository redhat-developer/gitops-operator, pull requests merged in 2025-07, with the labels that each got.

#919 Update to latest version of Argo Rollouts Route plugin E2E tests on 'v1.16' branch
  scripts/run-rollouts-e2e-tests.sh
Labels: kind/enhancement, lgtm, approved

#918 Upgrade Argo CD to v3 in GitOps operator
  .ci-operator.yaml
  Dockerfile
  Makefile
  bundle/manifests/argoproj.io_applications.yaml
  bundle/manifests/argoproj.io_applicationsets.yaml
  bundle/manifests/argoproj.io_appprojects.yaml
  bundle/manifests/argoproj.io_argocds.yaml
  bundle/manifests/argoproj.io_notificationsconfigurations.yaml
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  bundle/manifests/pipelines.openshift.io_gitopsservices.yaml
  cmd/main.go
  config/crd/bases/argoproj.io_applications.yaml
  config/crd/bases/argoproj.io_applicationsets.yaml
  config/crd/bases/argoproj.io_appprojects.yaml
  config/crd/bases/argoproj.io_argocds.yaml
  config/crd/bases/argoproj.io_notificationsconfigurations.yaml
  config/crd/bases/pipelines.openshift.io_gitopsservices.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  hack/upgrade-rollouts-manager/go.sum
  openshift-ci/build-root/Dockerfile
  scripts/openshiftci-presubmit-all-tests.sh
  scripts/openshiftci-presubmit-unittests.sh
  test/e2e/suite_test.go
  test/nondefaulte2e/suite_test.go
  test/openshift/e2e/ginkgo/fixture/application/fixture.go
  test/openshift/e2e/ginkgo/fixture/utils/fixtureUtils.go
  test/openshift/e2e/ginkgo/parallel/1-005_validate_route_tls_test.go
  test/openshift/e2e/ginkgo/parallel/1-008_validate-custom-argocd-namespace_test.go
  test/openshift/e2e/ginkgo/parallel/1-009_validate-manage-other-namespace_test.go
  test/openshift/e2e/ginkgo/parallel/1-012_validate-managed-by-chain_test.go
  test/openshift/e2e/ginkgo/parallel/1-019_validate_volume_mounts_test.go
  test/openshift/e2e/ginkgo/parallel/1-023_validate_repo_server_tls_test.go
  test/openshift/e2e/ginkgo/parallel/1-025-validate-managed-by-change_test.go
  test/openshift/e2e/ginkgo/parallel/1-031_validate_toolchain_test.go
  test/openshift/e2e/ginkgo/parallel/1-034_validate_webhook_notifications_test.go
  test/openshift/e2e/ginkgo/parallel/1-054_validate_deploymentconfig_test.go
  test/openshift/e2e/ginkgo/parallel/1-057_validate_notifications_test.go
  test/openshift/e2e/ginkgo/parallel/1-058_validate_prometheus_rule_test.go
  test/openshift/e2e/ginkgo/parallel/1-067_validate_redis_secure_comm_no_autotls_ha_test.go
  test/openshift/e2e/ginkgo/parallel/1-069_validate_redis_secure_comm_autotls_ha_test.go
  test/openshift/e2e/ginkgo/parallel/1-070_validate_config_management_plugin_test.go
  test/openshift/e2e/ginkgo/parallel/1-083_validate_kustomize_namereference_test.go
  test/openshift/e2e/ginkgo/parallel/1-116_annotation-based-tracking_test.go
  test/openshift/e2e/ginkgo/sequential/1-006_validate_machine_config_test.go
  test/openshift/e2e/ginkgo/sequential/1-008_validate-4.9CI-Failures_test.go
  test/openshift/e2e/ginkgo/sequential/1-010_validate-ootb-manage-other-namespace_test.go
  test/openshift/e2e/ginkgo/sequential/1-020_validate_redis_ha_nonha_test.go
  test/openshift/e2e/ginkgo/sequential/1-027_validate_operand_from_git_test.go
  test/openshift/e2e/ginkgo/sequential/1-064_validate_tcp_reset_error_test.go
  test/openshift/e2e/ginkgo/sequential/1-102_validate_handle_terminating_namespaces_test.go
  test/openshift/e2e/ginkgo/sequential/1-108_alternate_cluster_roles_cluster_scoped_instance_test.go
Labels: lgtm, approved, ok-to-test

#922 Update Ginkgo E2E test docs
  test/openshift/e2e/README.md
Labels: kind/documentation

#935 chore: update argocd-operator version
  go.mod
  go.sum
Labels: kind/bug
