Repository redhat-developer/gitops-operator, pull requests merged in 2025-03, with the labels that each got.

#859 chore: upgrade Argo CD to v2.12.10
  go.mod
  go.sum
  test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml
  test/openshift/e2e/sequential/1-040_validate_quoted_RBAC_group_names/01-login_argocd_api_server.yaml
Labels: lgtm, approved

#862 Downgrade v1.16 to Argo Rollouts Manager v0.0.5
  bundle/manifests/argoproj.io_analysisruns.yaml
  bundle/manifests/argoproj.io_analysistemplates.yaml
  bundle/manifests/argoproj.io_clusteranalysistemplates.yaml
  bundle/manifests/argoproj.io_experiments.yaml
  bundle/manifests/argoproj.io_rollouts.yaml
  config/crd/bases/analysis-run-crd.yaml
  config/crd/bases/analysis-template-crd.yaml
  config/crd/bases/cluster-analysis-template-crd.yaml
  config/crd/bases/experiment-crd.yaml
  config/crd/bases/rollout-crd.yaml
  go.mod
  go.sum
  scripts/run-rollouts-e2e-tests.sh
Labels: lgtm, approved, kind/cleanup

#858 Update v1.15 branch to point to Rollouts E2E test fixes
  scripts/run-rollouts-e2e-tests.sh
Labels: lgtm, approved, kind/failing-test

#837 Update OWNERS to reflect current contributors
  OWNERS
Labels: lgtm

#865 GITOPS-6495 fix for cmp server crashing with busybox image
  go.mod
  go.sum
Labels: kind/bug, lgtm, approved

#866 GITOPS-6495 fix for cmp server crashing with busybox image (#865)
  go.mod
  go.sum
Labels: kind/bug, lgtm, approved

#864 Update to latest commit of argo-rollouts-manager 'bb5580b286c595f91dfc21382df494e5fb8f9a46'
  go.mod
  go.sum
  scripts/run-rollouts-e2e-tests.sh
Labels: lgtm
