Repository redhat-developer/gitops-operator, pull requests merged in 2025-08, with the labels that each got.

#938 Fix mount issue with rollouts ui container
  go.mod
  go.sum
Labels: lgtm, approved

#941 Update to latest commit of argo-rollouts-manager 'a100fc1d88b8e3eee5d0d31a8be2956f96005d77' and argocd-operator '5135028d69782184553b57088981c72125aa77d7'
  Makefile
  bundle/manifests/argoproj.io_applications.yaml
  bundle/manifests/argoproj.io_applicationsets.yaml
  bundle/manifests/argoproj.io_appprojects.yaml
  bundle/manifests/argoproj.io_argocds.yaml
  bundle/manifests/argoproj.io_namespacemanagements.yaml
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  cmd/main.go
  config/crd/bases/argoproj.io_applications.yaml
  config/crd/bases/argoproj.io_applicationsets.yaml
  config/crd/bases/argoproj.io_appprojects.yaml
  config/crd/bases/argoproj.io_argocds.yaml
  config/crd/bases/argoproj.io_namespacemanagements.yaml
  config/crd/bases/argoproj.io_notificationsconfigurations.yaml
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  controllers/argocd_controller_test.go
  controllers/gitopsservice_controller.go
  go.mod
  go.sum
  scripts/run-rollouts-e2e-tests.sh
  test/e2e/suite_test.go
  test/nondefaulte2e/suite_test.go
  test/openshift/e2e/ginkgo/parallel/1-031_validate_toolchain_test.go
Labels: lgtm

#913 feat: watch and reconcile updates to the admin clusterrole
  cmd/main.go
  controllers/argocd/openshift/openshift.go
  controllers/argocd/openshift/openshift_test.go
Labels: kind/enhancement

#934 Introduce new label on operator managed configmap
  controllers/argocd_metrics_controller.go
  controllers/consoleplugin.go
Labels: lgtm, approved, ok-to-test
