Repository redhat-developer/gitops-operator, pull requests merged in 2025-10, with the labels that each got.

#953 chore: Update to latest argocd-operator commit '75b2e086ba211654deff43f975d8c2959108b710'
  .ci-operator.yaml
  go.mod
  go.sum
  openshift-ci/build-root/Dockerfile
  test/openshift/e2e/ginkgo/parallel/1-031_validate_toolchain_test.go
Labels: lgtm, approved

#980 fix: Fips ssh fix
  .ci-operator.yaml
  cmd/main.go
  go.mod
  go.sum
  openshift-ci/build-root/Dockerfile
  test/openshift/e2e/ginkgo/parallel/1-031_validate_toolchain_test.go
Labels: kind/bug

#981 chore: update to latest argocd-operator commit 'ef7197954c1d2ba5b3f733406d294956a78d423a'
  bundle/manifests/argoproj.io_argocds.yaml
  cmd/main.go
  config/crd/bases/argoproj.io_argocds.yaml
  go.mod
  go.sum
  test/openshift/e2e/ginkgo/fixture/deployment/fixture.go
  test/openshift/e2e/ginkgo/fixture/fixture.go
  test/openshift/e2e/ginkgo/parallel/1-023_validate_repo_server_tls_test.go
  test/openshift/e2e/ginkgo/parallel/1-042_restricted_pss_compliant_test.go
  test/openshift/e2e/ginkgo/parallel/1-066_validate_redis_secure_comm_no_autotls_no_ha_test.go
  test/openshift/e2e/ginkgo/parallel/1-067_validate_redis_secure_comm_no_autotls_ha_test.go
  test/openshift/e2e/ginkgo/parallel/1-069_validate_redis_secure_comm_autotls_ha_test.go
Labels: lgtm, approved, kind/cleanup

#984 Downstream securityContext changes
  go.mod
  go.sum
Labels: lgtm, approved, ok-to-test

#976 [GITOPS-7844]: GitOpsService controller creates default ArgoCD with v1alpha1 api version
  controllers/argocd/argocd.go
  controllers/gitopsservice_controller.go
Labels: kind/bug, lgtm, approved
