Repository redhat-developer/gitops-operator, pull requests merged in 2025-02, with the labels that each got.

#825 Add additional debugging to test command execution
  test/e2e/argocd_metrics_test.go
  test/e2e/gitopsservice_test.go
Labels: lgtm, approved

#826 Update to latest commit of argo-rollouts-manager 'b4635b5b8dd1f9683a25df512fec7169cab4403c'
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  scripts/run-rollouts-e2e-tests.sh
Labels: lgtm

#841 chore: update argocd-operator version
  go.mod
  go.sum
Labels: lgtm, approved

#843 Update to latest commit of argo-rollouts-manager '38faac6d4127850207da231d153526a3777fa3bf'
  bundle/manifests/argoproj.io_analysisruns.yaml
  bundle/manifests/argoproj.io_analysistemplates.yaml
  bundle/manifests/argoproj.io_clusteranalysistemplates.yaml
  bundle/manifests/argoproj.io_experiments.yaml
  bundle/manifests/argoproj.io_rollouts.yaml
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/crd/bases/analysis-run-crd.yaml
  config/crd/bases/analysis-template-crd.yaml
  config/crd/bases/cluster-analysis-template-crd.yaml
  config/crd/bases/experiment-crd.yaml
  config/crd/bases/rollout-crd.yaml
  go.mod
  go.sum
  scripts/run-rollouts-e2e-tests.sh
  test/openshift/e2e/sequential/1-040_validate_quoted_RBAC_group_names/01-login_argocd_api_server.yaml
Labels: lgtm, approved

#842 Fix interop test failures
  test/openshift/e2e/sequential/1-035_validate_argocd_secret_repopulate/05-argocd_login.yaml
  test/openshift/e2e/sequential/1-040_validate_quoted_RBAC_group_names/01-login_argocd_api_server.yaml
Labels: lgtm, approved, kind/failing-test

#844 feat: Support multiple ArgoCD instances with ApplicationTrackingAnnotations
  bundle/manifests/argoproj.io_argocds.yaml
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/crd/bases/argoproj.io_argocds.yaml
  go.mod
  go.sum
Labels: lgtm, approved, ok-to-test

#846 chore(deps): bump github.com/argoproj-labs/argocd-operator
  go.mod
  go.sum
  test/openshift/e2e/ignore-tests/parallel/1-064_validate_security_contexts/01-assert.yaml
  test/openshift/e2e/parallel/1-064_validate_security_contexts/01-assert.yaml
  test/openshift/e2e/sequential/1-107_validate_redis_ssc/01-assert.yaml
  test/openshift/e2e/sequential/1-107_validate_redis_ssc/01-install.yaml
  test/openshift/e2e/sequential/1-107_validate_redis_ssc/02-check-ha-redis-server-ssc.yaml
  test/openshift/e2e/sequential/1-107_validate_redis_ssc/03-check-ha-proxy-ssc.yaml
Labels: lgtm, approved

#845 fix: Add missing impersonate rule
  controllers/argocd/openshift/openshift.go
  controllers/argocd/openshift/openshift_test.go
Labels: kind/enhancement, lgtm, approved
