Repository redhat-developer/gitops-operator, pull requests merged in 2025-05, with the labels that each got.

#887 update argocd-operator crd and dep
  bundle/manifests/argoproj.io_argocds.yaml
  bundle/manifests/gitops-operator.clusterserviceversion.yaml
  config/crd/bases/argoproj.io_argocds.yaml
  go.mod
  go.sum
  test/openshift/e2e/parallel/1-083_validate_resource_customization_subkeys/01-assert.yaml
Labels: kind/enhancement, lgtm, approved

#891 Upgrade to latest commit from argo-cd operator '5234798de2caa16eb8464808cb8e7dbc8171cd2e'
  go.mod
  go.sum
  test/openshift/e2e/sequential/1-050_validate_sso/07-assert.yaml
  test/openshift/e2e/sequential/1-086_validate_default_argocd_role/02-install.yaml
Labels: kind/enhancement, lgtm, approved

#892 fix: add security context to plugin deployment
  controllers/consoleplugin.go
  controllers/consoleplugin_test.go
Labels: kind/bug

#893 chore: Update argocd-operator to latest for v1.15.3
  go.mod
  go.sum
Labels: kind/bug

#894 Modify SSO test
  test/openshift/e2e/sequential/1-050_validate_sso/03-assert.yaml
  test/openshift/e2e/sequential/1-050_validate_sso/03-errors.yaml
  test/openshift/e2e/sequential/1-050_validate_sso/03-provider-keycloak-dex-spec.yaml
  test/openshift/e2e/sequential/1-050_validate_sso/08-assert.yaml
  test/openshift/e2e/sequential/1-050_validate_sso/08-remove-spec-dex.yaml
Labels: lgtm, approved, kind/failing-test

#897 cherrypick fix CVE namespace-isolation break
  controllers/argocd_metrics_controller.go
  controllers/argocd_metrics_controller_test.go
Labels: kind/bug, lgtm, approved
