Repository redhat-developer/gitops-operator, pull requests merged in 2025-04, with the labels that each got.

#870 Re-enable fix for multi-arch Argo Rollouts E2E test images (v1.16)
  scripts/run-rollouts-e2e-tests.sh
Labels: lgtm, approved, kind/failing-test

#873 ci: Correct path in bundle push job
  .tekton/openshift-gitops-operator-bundle-push.yaml
Labels: kind/bug, lgtm, approved

#868 [1.14] fix CVE namespace-isolation break CVE-13484
  controllers/argocd_metrics_controller.go
  controllers/argocd_metrics_controller_test.go
Labels: kind/bug, lgtm, approved

#872 Re-enable fix for multi-arch Argo Rollouts E2E test images (master branch)
  scripts/run-rollouts-e2e-tests.sh
Labels: lgtm, approved, kind/failing-test

#875 Update v1.15 branch to argo-rollouts E2E tests latest v1.15 branch scripts
  scripts/run-rollouts-e2e-tests.sh
Labels: kind/bug, lgtm, approved

#876 Switch to quay.io repo for nginx-unprivileged image to avoid docker hub rate limiting
  test/examples/nginx/nginx.yaml
Labels: kind/bug, lgtm, approved

#878 Update to latest commit of argocd-operator
  go.mod
  go.sum
  test/openshift/e2e/parallel/1-019_validate_volume_mounts/01-assert.yaml
  test/openshift/e2e/parallel/1-104_validate_applicationset_tls_scm_volume_mount/01-assert.yaml
Labels: kind/enhancement, lgtm, approved

#884 GITOPS-6759: bump github.com/argoproj-labs/argocd-operator
  go.mod
  go.sum
Labels: lgtm, approved, ok-to-test

#882 Backport Subscription update logic for v1.15 Rollouts E2E tests
  scripts/run-rollouts-e2e-tests.sh
Labels: kind/enhancement, lgtm

#879 Update test image in Dockerfile
  openshift-ci/build-root/Dockerfile
Labels: lgtm, approved

#886 Update to latest argocd-operator commit 'd0b8ed3882c1bdb021e4b399537dede333cb1cfe' and argo-rollouts-manager commit 'a07ef1782da6cd99da6ed58e223136deb90ab4af'
  bundle/manifests/argoproj.io_argocds.yaml
  cmd/main.go
  config/crd/bases/argoproj.io_applications.yaml
  config/crd/bases/argoproj.io_applicationsets.yaml
  config/crd/bases/argoproj.io_argocds.yaml
  config/crd/bases/argoproj.io_notificationsconfigurations.yaml
  controllers/argocd_metrics_controller.go
  controllers/argocd_metrics_controller_test.go
  go.mod
  go.sum
  scripts/run-rollouts-e2e-tests.sh
  test/e2e/argocd_metrics_test.go
  test/e2e/gitopsservice_test.go
  test/e2e/suite_test.go
  test/nondefaulte2e/gitops_service_nondefault_test.go
  test/nondefaulte2e/suite_test.go
  test/openshift/e2e/parallel/1-104_validate_applicationset_tls_scm_volume_mount/01-assert.yaml
Labels: kind/enhancement, lgtm
